;;;; allocation VOPs for the WebAssembly target

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.
;;;;
;;;; This software is derived from the CMU CL system, which was
;;;; written at Carnegie Mellon University and released into the
;;;; public domain. The software is in the public domain and is
;;;; provided with absolutely no warranty. See the COPYING and CREDITS
;;;; files for more information.

(in-package "SB-VM")

;;; Inline allocation (bump allocation against the thread's region with a
;;; slow path into the runtime) is written in Sprint 3; see
;;; doc/wasm-port/02-design.md, 2.8. Until then the generators signal an
;;; error at code-generation time so that nothing silently emits bad code.
(defun allocation-not-yet-implemented (vop-name)
  (bug "~S: allocation is not implemented on this target yet" vop-name))

(define-vop (fixed-alloc)
  (:args)
  (:info name words type lowtag stack-allocate-p)
  (:ignore name words type lowtag stack-allocate-p)
  (:results (result :scs (descriptor-reg)))
  (:ignore result)
  (:generator 4
    (allocation-not-yet-implemented 'fixed-alloc)))

(define-vop (var-alloc)
  (:args (extra :scs (any-reg)))
  (:arg-types positive-fixnum)
  (:info name words type lowtag stack-allocate-p)
  (:ignore name words type lowtag stack-allocate-p extra)
  (:results (result :scs (descriptor-reg)))
  (:ignore result)
  (:generator 6
    (allocation-not-yet-implemented 'var-alloc)))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (list)
  (:args (things :scs (any-reg descriptor-reg control-stack) :load-if nil :more t))
  (:results (result :scs (descriptor-reg)))
  (:info star cons-cells)
  (:generator 0 (vop-not-yet-implemented 'list things result star cons-cells)))

(define-vop (make-closure)
  (:args (function :scs (descriptor-reg)))
  (:results (result :scs (descriptor-reg)))
  (:info label length stack-allocate-p)
  (:generator 10 (vop-not-yet-implemented 'make-closure function result label length stack-allocate-p)))

(define-vop (make-unbound-marker)
  (:args)
  (:results (result :scs (descriptor-reg any-reg)))
  (:generator 1 (vop-not-yet-implemented 'make-unbound-marker result)))

(define-vop (make-value-cell)
  (:args (value :scs (descriptor-reg any-reg)))
  (:results (result :scs (descriptor-reg)))
  (:generator 10 (vop-not-yet-implemented 'make-value-cell value result)))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (make-fdefn)
  (:args (name :scs (descriptor-reg)))
  (:results (result :scs (descriptor-reg)))
  (:translate make-fdefn)
  (:policy :fast-safe)
  (:generator 37 (vop-not-yet-implemented 'make-fdefn name result)))

(define-vop (allocate-vector-on-heap)
  (:args (type :scs (unsigned-reg)) (length :scs (any-reg)) (words :scs (any-reg)))
  (:results (result :scs (descriptor-reg)))
  (:arg-types (:or positive-fixnum) (:or positive-fixnum) (:or positive-fixnum))
  (:policy :fast-safe)
  (:generator 100 (vop-not-yet-implemented 'allocate-vector-on-heap type length words result)))

(define-vop (allocate-vector-on-stack)
  (:args (type :scs (unsigned-reg)) (length :scs (any-reg)) (words :scs (any-reg)))
  (:results (result :scs (descriptor-reg)))
  (:arg-types (:or positive-fixnum) (:or positive-fixnum) (:or positive-fixnum))
  (:policy :fast-safe)
  (:vop-var vop)
  (:generator 100 (vop-not-yet-implemented 'allocate-vector-on-stack type length words result)))
