;;;; c-call VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;; The C calling convention (argument registers and the number stack
;;; frame for a call-out) is written in Sprint 3.
(defun make-call-out-tns (type)
  (declare (ignore type))
  (vop-not-yet-implemented 'make-call-out-tns))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (alloc-number-stack-space)
  (:args)
  (:results (result :scs (sap-reg any-reg)))
  (:result-types (:or system-area-pointer))
  (:info amount)
  (:generator 0 (vop-not-yet-implemented 'alloc-number-stack-space result amount)))

(define-vop (call-out)
  (:args (function :scs (sap-reg)) (args :load-if nil :more t))
  (:results (results :load-if nil :more t))
  (:save-p t)
  (:vop-var vop)
  (:generator 0 (vop-not-yet-implemented 'call-out function args results)))

(define-vop (dealloc-number-stack-space)
  (:args)
  (:info amount)
  (:policy :fast-safe)
  (:generator 0 (vop-not-yet-implemented 'dealloc-number-stack-space amount)))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (foreign-symbol-sap)
  (:args)
  (:results (res :scs (sap-reg)))
  (:arg-types (:constant simple-string))
  (:result-types (:or system-area-pointer))
  (:info foreign-symbol)
  (:translate foreign-symbol-sap)
  (:policy :fast-safe)
  (:generator 2 (vop-not-yet-implemented 'foreign-symbol-sap res foreign-symbol)))

(define-vop (foreign-symbol-dataref-sap)
  (:args)
  (:results (res :scs (sap-reg)))
  (:arg-types (:constant simple-string))
  (:result-types (:or system-area-pointer))
  (:info foreign-symbol)
  (:translate foreign-symbol-dataref-sap)
  (:policy :fast-safe)
  (:generator 2 (vop-not-yet-implemented 'foreign-symbol-dataref-sap res foreign-symbol)))
