;;;; c-call VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;; TN allocation for a call-out. Every argument is passed on the number
;;; stack (in word slots, doubles taking two); the CALL-OUT VOP of the
;;; foreign-call sprint pushes them on the Wasm operand stack from there.
;;; Integer and pointer results come back in NL0 (and NL1 for a second
;;; value), float results in float register 0.

(defstruct arg-state
  (stack-frame-size 0))

(defstruct (result-state (:copier nil))
  (num-results 0))

(defun result-reg-offset (slot)
  (ecase slot
    (0 nl0-offset)
    (1 nl1-offset)))

(defun stack-arg-tn (state prim-type stack-sc &optional (words 1))
  (let ((frame-size (arg-state-stack-frame-size state)))
    (setf (arg-state-stack-frame-size state) (+ frame-size words))
    (make-wired-tn* prim-type stack-sc frame-size)))

(define-alien-type-method (integer :arg-tn) (type state)
  (if (alien-integer-type-signed type)
      (stack-arg-tn state 'signed-byte-32 signed-stack-sc-number)
      (stack-arg-tn state 'unsigned-byte-32 unsigned-stack-sc-number)))

(define-alien-type-method (system-area-pointer :arg-tn) (type state)
  (declare (ignore type))
  (stack-arg-tn state 'system-area-pointer sap-stack-sc-number))

(define-alien-type-method (single-float :arg-tn) (type state)
  (declare (ignore type))
  (stack-arg-tn state 'single-float single-stack-sc-number))

(define-alien-type-method (double-float :arg-tn) (type state)
  (declare (ignore type))
  (stack-arg-tn state 'double-float double-stack-sc-number 2))

(define-alien-type-method (integer :result-tn) (type state)
  (let ((num-results (result-state-num-results state)))
    (setf (result-state-num-results state) (1+ num-results))
    (multiple-value-bind (ptype reg-sc)
        (if (alien-integer-type-signed type)
            (values 'signed-byte-32 signed-reg-sc-number)
            (values 'unsigned-byte-32 unsigned-reg-sc-number))
      (make-wired-tn* ptype reg-sc (result-reg-offset num-results)))))

(define-alien-type-method (system-area-pointer :result-tn) (type state)
  (declare (ignore type state))
  (make-wired-tn* 'system-area-pointer sap-reg-sc-number (result-reg-offset 0)))

(define-alien-type-method (single-float :result-tn) (type state)
  (declare (ignore type state))
  (make-wired-tn* 'single-float single-reg-sc-number 0))

(define-alien-type-method (double-float :result-tn) (type state)
  (declare (ignore type state))
  (make-wired-tn* 'double-float double-reg-sc-number 0))

(define-alien-type-method (values :result-tn) (type state)
  (let ((values (alien-values-type-values type)))
    (when (> (length values) 2)
      (error "Too many result values from c-call."))
    (mapcar (lambda (type)
              (invoke-alien-type-method :result-tn type state))
            values)))

(define-alien-type-method (integer :naturalize-gen) (type alien)
  (if (and (not (alien-integer-type-signed type))
           (= (alien-type-bits type) 32))
      `(logand ,alien ,(1- (ash 1 (alien-type-bits type))))
      alien))

(defun make-call-out-tns (type)
  (let ((arg-state (make-arg-state)))
    (collect ((arg-tns))
      (dolist (arg-type (alien-fun-type-arg-types type))
        (arg-tns (invoke-alien-type-method :arg-tn arg-type arg-state)))
      (values (make-wired-tn* 'positive-fixnum any-reg-sc-number nsp-offset)
              (* (arg-state-stack-frame-size arg-state) n-word-bytes)
              (arg-tns)
              (invoke-alien-type-method :result-tn
                                        (alien-fun-type-result-type type)
                                        (make-result-state))))))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (alloc-number-stack-space)
  (:args)
  (:results (result :scs (sap-reg any-reg)))
  (:result-types (:or system-area-pointer))
  (:info amount)
  (:generator 0 (vop-not-yet-implemented 'alloc-number-stack-space result amount)))

(define-vop (call-out)
  (:args (function :scs (sap-reg)) (args :load-if nil :more t))
  (:results (results :load-if nil :more t))
  (:save-p t)
  (:vop-var vop)
  (:generator 0 (vop-not-yet-implemented 'call-out function args results)))

(define-vop (dealloc-number-stack-space)
  (:args)
  (:info amount)
  (:policy :fast-safe)
  (:generator 0 (vop-not-yet-implemented 'dealloc-number-stack-space amount)))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (foreign-symbol-sap)
  (:args)
  (:results (res :scs (sap-reg)))
  (:arg-types (:constant simple-string))
  (:result-types (:or system-area-pointer))
  (:info foreign-symbol)
  (:translate foreign-symbol-sap)
  (:policy :fast-safe)
  (:generator 2 (vop-not-yet-implemented 'foreign-symbol-sap res foreign-symbol)))

(define-vop (foreign-symbol-dataref-sap)
  (:args)
  (:results (res :scs (sap-reg)))
  (:arg-types (:constant simple-string))
  (:result-types (:or system-area-pointer))
  (:info foreign-symbol)
  (:translate foreign-symbol-dataref-sap)
  (:policy :fast-safe)
  (:generator 2 (vop-not-yet-implemented 'foreign-symbol-dataref-sap res foreign-symbol)))
