;;;; the VM definition of function call for the WebAssembly target

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.
;;;;
;;;; This software is derived from the CMU CL system, which was
;;;; written at Carnegie Mellon University and released into the
;;;; public domain. The software is in the public domain and is
;;;; provided with absolutely no warranty. See the COPYING and CREDITS
;;;; files for more information.

(in-package "SB-VM")

;;;; Interfaces to IR2 conversion:



;;; The return-point descriptor of a call is passed in RA (see vm.lisp).
(defun make-return-pc-passing-location ()
  (make-wired-tn *fixnum-primitive-type* any-reg-sc-number ra-offset))

(defun make-old-fp-passing-location ()
  (make-wired-tn *fixnum-primitive-type* any-reg-sc-number ocfp-offset))

(defconstant old-fp-passing-offset
  (make-sc+offset descriptor-reg-sc-number ocfp-offset))

;;; Make the TNs used to hold OLD-FP and RETURN-PC within the current
;;; function. We treat these specially so that the debugger can find them
;;; at a known location.
(defun make-old-fp-save-location (env)
  (specify-save-tn
   (environment-debug-live-tn (make-normal-tn *fixnum-primitive-type*) env)
   (make-wired-tn *fixnum-primitive-type* control-stack-sc-number ocfp-save-offset)))

(defun make-return-pc-save-location (env)
  (let ((ptype *fixnum-primitive-type*))
    (specify-save-tn
     (environment-debug-live-tn
      (make-wired-tn *fixnum-primitive-type* any-reg-sc-number ra-offset)
      env)
     (make-wired-tn ptype control-stack-sc-number ra-save-offset))))

;;; Make a TN for the standard argument count passing location.
(defun make-arg-count-location ()
  (make-wired-tn *fixnum-primitive-type* any-reg-sc-number nargs-offset))





;;; This function is called by the ENTRY-ANALYZE phase, allowing
;;; VM-dependent initialization of the IR2-COMPONENT structure. We push
;;; placeholder entries in the CONSTANTS to leave room for additional
;;; noise in the code object header.
(defun select-component-format (component)
  (declare (type component component))
  (dotimes (i code-constants-offset)
    (vector-push-extend nil
                        (ir2-component-constants (component-info component))))
  (values))

;;; Emit the label of an IR2 block. Every block becomes an arm of the
;;; function's dispatcher (see func-asm.lisp); no alignment, and no
;;; trampolines are needed since local calls are direct.
(defun emit-block-header (start-label trampoline-label fall-thru-p alignp)
  (declare (ignore fall-thru-p alignp))
  (when trampoline-label
    (emit-label trampoline-label))
  (emit-label start-label))

;;; The calling convention itself (frames, XEPs, full and local calls,
;;; returns, tail calls) is written in Sprint 3; see
;;; doc/wasm-port/02-design.md, 2.4.

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (allocate-frame)
  (:args)
  (:results (res :scs (any-reg)) (nfp :scs (any-reg)))
  (:info callee)
  (:generator 2 (vop-not-yet-implemented 'allocate-frame res nfp callee)))

(define-vop (allocate-full-call-frame)
  (:args)
  (:results (res :scs (any-reg)))
  (:info nargs)
  (:generator 2 (vop-not-yet-implemented 'allocate-full-call-frame res nargs)))

(define-vop (ancestor-frame-ref)
  (:args (frame-pointer :scs (descriptor-reg)) (variable-home-tn :load-if nil))
  (:results (value :scs (descriptor-reg any-reg)))
  (:policy :fast-safe)
  (:generator 4 (vop-not-yet-implemented 'ancestor-frame-ref frame-pointer variable-home-tn value)))

(define-vop (ancestor-frame-set)
  (:args (frame-pointer :scs (descriptor-reg)) (value :scs (descriptor-reg any-reg)))
  (:results (variable-home-tn :load-if nil))
  (:generator 4 (vop-not-yet-implemented 'ancestor-frame-set frame-pointer value variable-home-tn)))

(define-vop (call)
  (:args (new-fp :scs (any-reg)) (arg-fun)
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:results (values :load-if nil :more t))
  (:info arg-locs nargs nvals step-instrumenting)
  (:save-p t)
  (:move-args :full-call)
  (:vop-var vop)
  (:generator 26 (vop-not-yet-implemented 'call new-fp arg-fun args values arg-locs nargs nvals step-instrumenting)))

(define-vop (call-local)
  (:args (fp) (nfp) (args :load-if nil :more t))
  (:results (values :load-if nil :more t))
  (:info arg-locs callee target nvals)
  (:save-p t)
  (:move-args :local-call)
  (:vop-var vop)
  (:generator 5 (vop-not-yet-implemented 'call-local fp nfp args values arg-locs callee target nvals)))

(define-vop (call-named)
  (:args (new-fp :scs (any-reg)) (name)
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:results (values :load-if nil :more t))
  (:info arg-locs nargs nvals step-instrumenting)
  (:save-p t)
  (:move-args :full-call)
  (:vop-var vop)
  (:generator 31 (vop-not-yet-implemented 'call-named new-fp name args values arg-locs nargs nvals step-instrumenting)))

(define-vop (call-variable)
  (:args (new-fp :scs (any-reg)) (arg-fun))
  (:results (values :load-if nil :more t))
  (:info nvals step-instrumenting)
  (:save-p t)
  (:vop-var vop)
  (:generator 44 (vop-not-yet-implemented 'call-variable new-fp arg-fun values nvals step-instrumenting)))

(define-vop (compute-old-nfp)
  (:args)
  (:results (val :scs (any-reg)))
  (:vop-var vop)
  (:generator 1 (vop-not-yet-implemented 'compute-old-nfp val)))

(define-vop (copy-more-arg)
  (:args)
  (:info fixed)
  (:vop-var vop)
  (:generator 20 (vop-not-yet-implemented 'copy-more-arg fixed)))

(define-vop (current-fp)
  (:args)
  (:results (val :scs (any-reg)))
  (:generator 1 (vop-not-yet-implemented 'current-fp val)))

(define-vop (known-call-local)
  (:args (fp) (nfp) (args :load-if nil :more t))
  (:results (res :load-if nil :more t))
  (:info save callee target)
  (:save-p t)
  (:move-args :local-call)
  (:vop-var vop)
  (:generator 5 (vop-not-yet-implemented 'known-call-local fp nfp args res save callee target)))

(define-vop (known-return)
  (:args (old-fp) (return-pc)
   (values :load-if nil :more t))
  (:info val-locs)
  (:move-args :known-return)
  (:vop-var vop)
  (:generator 6 (vop-not-yet-implemented 'known-return old-fp return-pc values val-locs)))

(define-vop (multiple-call)
  (:args (new-fp :scs (any-reg)) (arg-fun)
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:info arg-locs nargs step-instrumenting)
  (:save-p t)
  (:move-args :full-call)
  (:vop-var vop)
  (:generator 51 (vop-not-yet-implemented 'multiple-call new-fp arg-fun args start count arg-locs nargs step-instrumenting)))

(define-vop (multiple-call-local)
  (:args (fp) (nfp) (args :load-if nil :more t))
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:info save callee target)
  (:save-p t)
  (:move-args :local-call)
  (:vop-var vop)
  (:generator 20 (vop-not-yet-implemented 'multiple-call-local fp nfp args start count save callee target)))

(define-vop (multiple-call-named)
  (:args (new-fp :scs (any-reg)) (name)
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:info arg-locs nargs step-instrumenting)
  (:save-p t)
  (:move-args :full-call)
  (:vop-var vop)
  (:generator 56 (vop-not-yet-implemented 'multiple-call-named new-fp name args start count arg-locs nargs step-instrumenting)))

(define-vop (multiple-call-variable)
  (:args (new-fp :scs (any-reg)) (arg-fun))
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:info step-instrumenting)
  (:save-p t)
  (:vop-var vop)
  (:generator 69 (vop-not-yet-implemented 'multiple-call-variable new-fp arg-fun start count step-instrumenting)))


(define-vop (return)
  (:args (old-fp :scs (any-reg)) (return-pc :scs (any-reg))
   (values :load-if nil :more t))
  (:info nvals)
  (:vop-var vop)
  (:generator 6 (vop-not-yet-implemented 'return old-fp return-pc values nvals)))

(define-vop (return-multiple)
  (:args (old-fp-arg :scs (any-reg)) (return-pc :scs (any-reg))
   (vals-arg :scs (any-reg)) (nvals-arg :scs (any-reg)))
  (:vop-var vop)
  (:generator 13 (vop-not-yet-implemented 'return-multiple old-fp-arg return-pc vals-arg nvals-arg)))

(define-vop (return-single)
  (:args (old-fp :scs (any-reg)) (return-pc :scs (any-reg)) (value))
  (:vop-var vop)
  (:generator 6 (vop-not-yet-implemented 'return-single old-fp return-pc value)))

(define-vop (setup-closure-environment)
  (:args)
  (:results (closure :scs (descriptor-reg)))
  (:info label)
  (:generator 6 (vop-not-yet-implemented 'setup-closure-environment closure label)))

(define-vop (static-call-named)
  (:args (new-fp :scs (any-reg))
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:results (values :load-if nil :more t))
  (:info arg-locs nargs fun nvals step-instrumenting)
  (:save-p t)
  (:move-args :full-call)
  (:vop-var vop)
  (:generator 31 (vop-not-yet-implemented 'static-call-named new-fp args values arg-locs nargs fun nvals step-instrumenting)))

(define-vop (static-multiple-call-named)
  (:args (new-fp :scs (any-reg))
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:info arg-locs nargs fun step-instrumenting)
  (:save-p t)
  (:move-args :full-call)
  (:vop-var vop)
  (:generator 56 (vop-not-yet-implemented 'static-multiple-call-named new-fp args start count arg-locs nargs fun step-instrumenting)))

(define-vop (static-tail-call-named)
  (:args (old-fp) (return-pc)
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:info nargs fun step-instrumenting)
  (:save-p :compute-only)
  (:vop-var vop)
  (:generator 21 (vop-not-yet-implemented 'static-tail-call-named old-fp return-pc args nargs fun step-instrumenting)))

(define-vop (tail-call)
  (:args (arg-fun) (old-fp)
   (return-pc)
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:info nargs step-instrumenting)
  (:save-p :compute-only)
  (:vop-var vop)
  (:generator 16 (vop-not-yet-implemented 'tail-call arg-fun old-fp return-pc args nargs step-instrumenting)))

(define-vop (tail-call-named)
  (:args (name) (old-fp)
   (return-pc)
   (args :scs (descriptor-reg control-stack) :load-if nil :more t))
  (:info nargs step-instrumenting)
  (:save-p :compute-only)
  (:vop-var vop)
  (:generator 21 (vop-not-yet-implemented 'tail-call-named name old-fp return-pc args nargs step-instrumenting)))

(define-vop (tail-call-variable)
  (:args (args-arg :scs (any-reg))
   (function-arg :scs (descriptor-reg))
   (old-fp-arg :scs (any-reg)) (ra-arg :scs (any-reg)))
  (:vop-var vop)
  (:generator 75 (vop-not-yet-implemented 'tail-call-variable args-arg function-arg old-fp-arg ra-arg)))

(define-vop (verify-arg-count)
  (:args (nargs :scs (any-reg)))
  (:arg-types (:or positive-fixnum) (:constant t) (:constant t))
  (:info min max)
  (:policy :fast-safe)
  (:save-p :compute-only)
  (:vop-var vop)
  (:generator 3 (vop-not-yet-implemented 'verify-arg-count nargs min max)))

(define-vop (xep-allocate-frame)
  (:args)
  (:info start-lab)
  (:generator 1 (vop-not-yet-implemented 'xep-allocate-frame start-lab)))

(define-vop (xep-setup-sp)
  (:args)
  (:vop-var vop)
  (:generator 1 (vop-not-yet-implemented 'xep-setup-sp )))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (more-arg-or-nil)
  (:args (object :scs (descriptor-reg)) (count :scs (any-reg)))
  (:results (value :scs (descriptor-reg any-reg)))
  (:result-types *)
  (:info index)
  (:policy :fast-safe)
  (:generator 3 (vop-not-yet-implemented 'more-arg-or-nil object count value index)))

(define-vop (step-instrument-before-vop)
  (:args)
  (:policy :fast-safe)
  (:vop-var vop)
  (:generator 3 (vop-not-yet-implemented 'step-instrument-before-vop )))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (call-into-lisp)
  (:args (function :scs (descriptor-reg any-reg))
   (arg-ptr :scs (descriptor-reg any-reg))
   (nargs :scs (any-reg)) (ra :scs (any-reg)))
  (:vop-var #:vop)
  (:generator 247 (vop-not-yet-implemented 'call-into-lisp function arg-ptr nargs ra)))

(define-vop (call-into-c)
  (:args (cfunc :scs (any-reg)))
  (:vop-var #:vop)
  (:generator 247 (vop-not-yet-implemented 'call-into-c cfunc)))

(define-vop (unknown-values-receiver)
  (:args)
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:generator 0 (vop-not-yet-implemented 'unknown-values-receiver start count)))

(define-vop (more-arg)
  (:args (object :scs (descriptor-reg)) (index :scs (any-reg)))
  (:results (value :scs (descriptor-reg any-reg)))
  (:arg-types * (:or positive-fixnum fixnum))
  (:result-types *)
  (:translate %more-arg)
  (:policy :fast-safe)
  (:generator 5 (vop-not-yet-implemented 'more-arg object index value)))

(define-vop (more-arg-c)
  (:args (object :scs (descriptor-reg)))
  (:results (value :scs (descriptor-reg any-reg)))
  (:arg-types * (:constant (load/store-index 4 0 0)))
  (:result-types *)
  (:info index)
  (:translate %more-arg)
  (:policy :fast-safe)
  (:generator 4 (vop-not-yet-implemented 'more-arg-c object value index)))

(define-vop (%listify-rest-args)
  (:args (context-arg :scs (descriptor-reg))
   (count-arg :scs (any-reg)))
  (:results (result :scs (descriptor-reg)))
  (:arg-types * (:or positive-fixnum fixnum))
  (:translate %listify-rest-args)
  (:policy :safe)
  (:generator 20 (vop-not-yet-implemented '%listify-rest-args context-arg count-arg result)))

(define-vop (sb-c::%more-arg-context)
  (:args (supplied :scs (any-reg)))
  (:results (context :scs (descriptor-reg)) (count :scs (any-reg)))
  (:arg-types (:or positive-fixnum fixnum) (:constant fixnum))
  (:result-types (:or t) (:or positive-fixnum fixnum))
  (:info fixed)
  (:translate sb-c::%more-arg-context)
  (:policy :fast-safe)
  (:note "more-arg-context")
  (:generator 5 (vop-not-yet-implemented 'sb-c::%more-arg-context supplied context count fixed)))




