;;;; char VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (move-to-character)
  (:args (x :scs (any-reg descriptor-reg)))
  (:results (y :scs (character-reg)))
  (:note "character untagging")
  (:generator 1 (vop-not-yet-implemented 'move-to-character x y)))

(define-vop (move-from-character)
  (:args (x :scs (character-reg)))
  (:results (y :scs (any-reg descriptor-reg)))
  (:note "character tagging")
  (:generator 1 (vop-not-yet-implemented 'move-from-character x y)))

(define-vop (character-move)
  (:args (x :scs (character-reg) :load-if (not (location= x y))))
  (:results (y :scs (character-reg) :load-if (not (location= x y))))
  (:note "character move")
  
  (:generator 0 (vop-not-yet-implemented 'character-move x y)))

(define-vop (move-character-arg)
  (:args (x :scs (character-reg))
   (fp :scs (any-reg) :load-if (not (sc-is y character-reg))))
  (:results (y))
  (:note "character arg move")
  (:generator 0 (vop-not-yet-implemented 'move-character-arg x fp y)))

(define-vop (char-code)
  (:args (ch :scs (character-reg)))
  (:results (res :scs (any-reg)))
  (:arg-types (:or character))
  (:result-types (:or positive-fixnum))
  (:translate char-code)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'char-code ch res)))

(define-vop (code-char)
  (:args (code :scs (any-reg)))
  (:results (res :scs (character-reg)))
  (:arg-types (:or positive-fixnum))
  (:result-types (:or character))
  (:translate code-char)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'code-char code res)))

(define-vop (character-compare)
  (:args (x :scs (character-reg)) (y :scs (character-reg)))
  (:arg-types (:or character) (:or character))
  (:result-types)
  (:info target not-p)
  (:conditional)
  (:policy :fast-safe)
  (:variant-vars condition)
  (:variant nil)
  (:note "inline comparison")
  (:generator 1 (vop-not-yet-implemented 'character-compare x y target not-p condition)))

(define-vop (fast-char=/character)
  (:args (x :scs (character-reg)) (y :scs (character-reg)))
  (:arg-types (:or character) (:or character))
  (:result-types)
  (:info target not-p)
  (:conditional)
  (:translate char=)
  (:policy :fast-safe)
  (:variant-vars condition)
  (:variant :eq)
  (:note "inline comparison")
  (:generator 1 (vop-not-yet-implemented 'fast-char=/character x y target not-p condition)))

(define-vop (fast-char</character)
  (:args (x :scs (character-reg)) (y :scs (character-reg)))
  (:arg-types (:or character) (:or character))
  (:result-types)
  (:info target not-p)
  (:conditional)
  (:translate char<)
  (:policy :fast-safe)
  (:variant-vars condition)
  (:variant :lt)
  (:note "inline comparison")
  (:generator 1 (vop-not-yet-implemented 'fast-char</character x y target not-p condition)))

(define-vop (fast-char>/character)
  (:args (x :scs (character-reg)) (y :scs (character-reg)))
  (:arg-types (:or character) (:or character))
  (:result-types)
  (:info target not-p)
  (:conditional)
  (:translate char>)
  (:policy :fast-safe)
  (:variant-vars condition)
  (:variant :gt)
  (:note "inline comparison")
  (:generator 1 (vop-not-yet-implemented 'fast-char>/character x y target not-p condition)))

