;;;; debug VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (current-fp-sap)
  (:args)
  (:results (res :scs (sap-reg)))
  (:result-types (:or system-area-pointer))
  (:translate current-fp)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'current-fp-sap res)))

(define-vop (code-from-mumble)
  (:args (thing :scs (descriptor-reg)))
  (:results (code :scs (descriptor-reg)))
  (:policy :fast-safe)
  (:variant-vars lowtag)
  (:variant nil)
  (:generator 5 (vop-not-yet-implemented 'code-from-mumble thing code lowtag)))

(define-vop (code-from-fun)
  (:args (thing :scs (descriptor-reg)))
  (:results (code :scs (descriptor-reg)))
  (:translate fun-code-header)
  (:policy :fast-safe)
  (:variant-vars lowtag)
  (:variant fun-pointer-lowtag)
  (:generator 5 (vop-not-yet-implemented 'code-from-fun thing code lowtag)))

(define-vop (%make-lisp-obj)
  (:args (value :scs (unsigned-reg)))
  (:results (result :scs (descriptor-reg)))
  (:arg-types (:or unsigned-byte-32 unsigned-byte-31 positive-fixnum))
  (:translate %make-lisp-obj)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented '%make-lisp-obj value result)))

(define-vop (get-lisp-obj-address)
  (:args (thing :scs (descriptor-reg any-reg)))
  (:results (result :scs (unsigned-reg)))
  (:result-types (:or unsigned-byte-32 unsigned-byte-31 positive-fixnum))
  (:translate get-lisp-obj-address)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'get-lisp-obj-address thing result)))
