;;;; memory VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (cell-ref)
  (:args (object :scs (descriptor-reg)))
  (:results (value :scs (descriptor-reg any-reg)))
  (:variant-vars offset lowtag)
  (:variant nil nil)
  (:generator 4 (vop-not-yet-implemented 'cell-ref object value offset lowtag)))

(define-vop (cell-set)
  (:args (object :scs (descriptor-reg)) (value :scs (descriptor-reg any-reg)))
  (:variant-vars offset lowtag)
  (:variant nil nil)
  (:generator 4 (vop-not-yet-implemented 'cell-set object value offset lowtag)))

(define-vop (set-instance-hashed)
  (:args (object :scs (descriptor-reg)))
  (:generator 5 (vop-not-yet-implemented 'set-instance-hashed object)))
