;;;; the WebAssembly VM definition of operand loading/saving and the MOVE vop

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.
;;;;
;;;; This software is derived from the CMU CL system, which was
;;;; written at Carnegie Mellon University and released into the
;;;; public domain. The software is in the public domain and is
;;;; provided with absolutely no warranty. See the COPYING and CREDITS
;;;; files for more information.

(in-package "SB-VM")

(define-move-fun (load-immediate 1) (vop x y)
  ((immediate)
   (any-reg descriptor-reg))
  (let ((val (tn-value x)))
    (etypecase val
      (integer
       (load-immediate-word y (fixnumize val)))
      (null
       (load-immediate-word y nil-value))
      (symbol
       (load-symbol y val))
      (character
       (load-immediate-word y (logior (ash (char-code val) n-widetag-bits)
                                      character-widetag)))
      (structure-object
       (if (eq val sb-lockless:+tail+)
           (load-immediate-word y (+ nil-value lflist-tail-value-nil-offset))
           (bug "immediate structure-object ~S" val))))))

(define-move-fun (load-number 1) (vop x y)
  ((immediate)
   (signed-reg unsigned-reg))
  (load-immediate-word y (tn-value x)))

(define-move-fun (load-character 1) (vop x y)
  ((immediate) (character-reg))
  (load-immediate-word y (char-code (tn-value x))))

(define-move-fun (load-system-area-pointer 1) (vop x y)
  ((immediate) (sap-reg))
  (load-immediate-word y (sap-int (tn-value x))))

(define-move-fun (load-constant 5) (vop x y)
  ((constant) (any-reg descriptor-reg))
  (loadw y code-tn (tn-offset x) other-pointer-lowtag))

(define-move-fun (load-stack 5) (vop x y)
  ((control-stack) (any-reg descriptor-reg))
  (load-stack-tn y x))

(define-move-fun (load-number-stack 5) (vop x y)
  ((character-stack) (character-reg)
   (sap-stack) (sap-reg)
   (signed-stack) (signed-reg)
   (unsigned-stack) (unsigned-reg))
  (load-frame-word y (current-nfp-tn vop) (tn-offset x)))

(define-move-fun (store-stack 5) (vop x y)
  ((any-reg descriptor-reg) (control-stack))
  (store-stack-tn y x))

(define-move-fun (store-number-stack 5) (vop x y)
  ((character-reg) (character-stack)
   (sap-reg) (sap-stack)
   (signed-reg) (signed-stack)
   (unsigned-reg) (unsigned-stack))
  (store-frame-word x (current-nfp-tn vop) (tn-offset y)))

;;;; The Move VOP:

(define-vop (move)
  (:args (x :target y
            :scs (any-reg descriptor-reg)
            :load-if (not (location= x y))))
  (:results (y :scs (any-reg descriptor-reg control-stack)
               :load-if (not (location= x y))))
  (:generator 0
    (unless (location= x y)
      (sc-case y
        ((any-reg descriptor-reg)
         (move y x))
        (control-stack
         (store-stack-tn y x))))))
(define-move-vop move :move
  (any-reg descriptor-reg)
  (any-reg descriptor-reg))


;;; The Move-Argument VOP is used for moving descriptor values into
;;; another frame for argument or known value passing. FP is the frame
;;; pointer of the callee frame.
(define-vop (move-arg)
  (:args (x :target y
            :scs (any-reg descriptor-reg))
         (fp :scs (any-reg)
             :load-if (not (sc-is y any-reg descriptor-reg))))
  (:results (y))
  (:generator 0
    (sc-case y
      ((any-reg descriptor-reg)
       (move y x))
      (control-stack
       (store-frame-word x fp (tn-offset y))))))

(define-move-vop move-arg :move-arg
  (any-reg descriptor-reg)
  (any-reg descriptor-reg))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (move-to-word/fixnum)
  (:args (x :scs (any-reg descriptor-reg)))
  (:results (y :scs (signed-reg unsigned-reg)))
  (:arg-types tagged-num)
  (:note "fixnum untagging")
  (:generator 1
    (store-reg y
      (load-reg x)
      (inst i32.const n-fixnum-tag-bits)
      (inst i32.shr_s))))
;;;; Move VOP registrations (coercions between storage classes), as on riscv.

(define-move-vop move-to-word/fixnum :move
  (any-reg descriptor-reg) (signed-reg unsigned-reg))


(define-vop (move-to-word-c)
  (:args (x :scs (constant)))
  (:results (y :scs (signed-reg unsigned-reg)))
  (:vop-var vop)
  (:note "constant load")
  (:generator 1
    (cond ((sb-c::tn-leaf x)
           (load-immediate-word y (tn-value x)))
          (t
           (load-constant vop x y)
           (store-reg y
             (load-reg y)
             (inst i32.const n-fixnum-tag-bits)
             (inst i32.shr_s))))))
(define-move-vop move-to-word-c :move
  (constant) (signed-reg unsigned-reg))


;;; A fixnum is untagged; a bignum's first digit is its value.
(define-vop (move-to-word/integer)
  (:args (x :scs (descriptor-reg)))
  (:results (y :scs (signed-reg unsigned-reg) :from :eval))
  (:note "integer to untagged word coercion")
  (:generator 3
    (let ((bignum (gen-label)) (done (gen-label)))
      (load-reg x)
      (inst i32.const fixnum-tag-mask)
      (inst i32.and)
      (inst jump-if bignum)
      (store-reg y
        (load-reg x)
        (inst i32.const n-fixnum-tag-bits)
        (inst i32.shr_s))
      (inst jump done)
      (emit-label bignum)
      (loadw y x bignum-digits-offset other-pointer-lowtag)
      (emit-label done))))
(define-move-vop move-to-word/integer :move
  (descriptor-reg) (signed-reg unsigned-reg))


(define-vop (move-from-word/fixnum)
  (:args (x :scs (signed-reg unsigned-reg) :target y))
  (:results (y :scs (any-reg descriptor-reg)))
  (:result-types tagged-num)
  (:note "fixnum tagging")
  (:generator 1
    (store-reg y
      (load-reg x)
      (inst i32.const n-fixnum-tag-bits)
      (inst i32.shl))))
(define-move-vop move-from-word/fixnum :move
  (signed-reg unsigned-reg) (any-reg descriptor-reg))


;;; A signed word that fits is tagged; otherwise a one-digit bignum is
;;; allocated. The word fits when shifting left by the tag bits and back
;;; gives the same value.
(define-vop (move-from-signed)
  (:args (arg :scs (signed-reg unsigned-reg) :target x))
  (:results (y :scs (any-reg descriptor-reg) :from :eval))
  (:temporary (:scs (non-descriptor-reg) :from (:argument 0)) x)
  (:note "signed word to integer coercion")
  (:generator 15
    (let ((bignum (gen-label)) (done (gen-label)))
      (move x arg)
      (store-reg y
        (load-reg x)
        (inst i32.const n-fixnum-tag-bits)
        (inst i32.shl))
      (load-reg y)
      (inst i32.const n-fixnum-tag-bits)
      (inst i32.shr_s)
      (load-reg x)
      (inst i32.ne)
      (inst jump-if bignum)
      (inst jump done)
      (emit-label bignum)
      (with-fixed-allocation (y bignum-widetag (1+ bignum-digits-offset))
        (storew x y bignum-digits-offset other-pointer-lowtag))
      (emit-label done))))
(define-move-vop move-from-signed :move
  (signed-reg) (descriptor-reg))


(define-vop (move-from-fixnum+/-1)
  (:args (x :scs (signed-reg unsigned-reg)))
  (:results (y :scs (any-reg descriptor-reg) :from :eval))
  (:vop-var vop)
  (:variant-vars constant)
  (:generator 4
    (let ((overflow (gen-label)) (done (gen-label)))
      (store-reg y
        (load-reg x)
        (inst i32.const n-fixnum-tag-bits)
        (inst i32.shl))
      (load-reg y)
      (inst i32.const n-fixnum-tag-bits)
      (inst i32.shr_s)
      (load-reg x)
      (inst i32.ne)
      (inst jump-if overflow)
      (inst jump done)
      (emit-label overflow)
      (load-constant vop (emit-constant constant) y)
      (emit-label done))))

(define-vop (move-from-fixnum+1 move-from-fixnum+/-1)
  (:variant (1+ most-positive-fixnum)))

(define-vop (move-from-fixnum-1 move-from-fixnum+/-1)
  (:variant (1- most-negative-fixnum)))

;;; An unsigned word that fits is tagged; otherwise a bignum of one or
;;; two digits (two when the top bit is set) is allocated.
(define-vop (move-from-unsigned)
  (:args (arg :scs (signed-reg unsigned-reg) :target x))
  (:results (y :scs (any-reg descriptor-reg) :from :eval))
  (:temporary (:scs (non-descriptor-reg) :from (:argument 0)) x)
  (:note "unsigned word to integer coercion")
  (:generator 20
    (let ((bignum (gen-label)) (done (gen-label)))
      (move x arg)
      (load-reg x)
      (inst i32.const n-positive-fixnum-bits)
      (inst i32.shr_u)
      (inst jump-if bignum)
      (store-reg y
        (load-reg x)
        (inst i32.const n-fixnum-tag-bits)
        (inst i32.shl))
      (inst jump done)
      (emit-label bignum)
      ;; two digits always, so that the sign digit is zero when needed
      (emit-allocate y (pad-data-block (+ bignum-digits-offset 2)) other-pointer-lowtag)
      (load-reg y)
      (emit-store-word (- other-pointer-lowtag)
        ;; header: length 1 if positive, 2 if the top bit is set
        (load-reg x)
        (inst i32.const 31)
        (inst i32.shr_u)
        (inst i32.const 1)
        (inst i32.add)
        (inst i32.const n-widetag-bits)
        (inst i32.shl)
        (inst i32.const bignum-widetag)
        (inst i32.or))
      (storew x y bignum-digits-offset other-pointer-lowtag)
      (load-reg y)
      (emit-store-word (- (ash (1+ bignum-digits-offset) word-shift) other-pointer-lowtag)
        (inst i32.const 0))
      (emit-label done))))
(define-move-vop move-from-unsigned :move
  (unsigned-reg) (descriptor-reg))


(define-vop (word-move)
  (:args (x :scs (signed-reg unsigned-reg) :target y
            :load-if (not (location= x y))))
  (:results (y :scs (signed-reg unsigned-reg)
               :load-if (not (location= x y))))
  (:note "word integer move")
  (:generator 0
    (move y x)))
(define-move-vop word-move :move
  (signed-reg unsigned-reg) (signed-reg unsigned-reg))


;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (move-word-arg)
  (:args (x :target y
            :scs (signed-reg unsigned-reg))
         (fp :scs (any-reg)
             :load-if (not (sc-is y signed-reg unsigned-reg))))
  (:results (y))
  (:note "word integer argument move")
  (:generator 0
    (sc-case y
      ((signed-reg unsigned-reg)
       (move y x))
      ((signed-stack unsigned-stack)
       (store-frame-word x fp (tn-offset y))))))

(define-move-vop move-word-arg :move-arg
  (descriptor-reg any-reg signed-reg unsigned-reg) (signed-reg unsigned-reg))

;;; Use standard MOVE-ARG + coercion to move an untagged number to a
;;; descriptor passing location.
(define-move-vop move-arg :move-arg
  (signed-reg unsigned-reg) (any-reg descriptor-reg))
