;;;; the WebAssembly VM definition of operand loading/saving and the MOVE vop

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.
;;;;
;;;; This software is derived from the CMU CL system, which was
;;;; written at Carnegie Mellon University and released into the
;;;; public domain. The software is in the public domain and is
;;;; provided with absolutely no warranty. See the COPYING and CREDITS
;;;; files for more information.

(in-package "SB-VM")

(define-move-fun (load-immediate 1) (vop x y)
  ((immediate)
   (any-reg descriptor-reg))
  (let ((val (tn-value x)))
    (etypecase val
      (integer
       (load-immediate-word y (fixnumize val)))
      (null
       (load-immediate-word y nil-value))
      (symbol
       (load-symbol y val))
      (character
       (load-immediate-word y (logior (ash (char-code val) n-widetag-bits)
                                      character-widetag)))
      (structure-object
       (if (eq val sb-lockless:+tail+)
           (load-immediate-word y (+ nil-value lflist-tail-value-nil-offset))
           (bug "immediate structure-object ~S" val))))))

(define-move-fun (load-number 1) (vop x y)
  ((immediate)
   (signed-reg unsigned-reg))
  (load-immediate-word y (tn-value x)))

(define-move-fun (load-character 1) (vop x y)
  ((immediate) (character-reg))
  (load-immediate-word y (char-code (tn-value x))))

(define-move-fun (load-system-area-pointer 1) (vop x y)
  ((immediate) (sap-reg))
  (load-immediate-word y (sap-int (tn-value x))))

(define-move-fun (load-constant 5) (vop x y)
  ((constant) (any-reg descriptor-reg))
  (loadw y code-tn (tn-offset x) other-pointer-lowtag))

(define-move-fun (load-stack 5) (vop x y)
  ((control-stack) (any-reg descriptor-reg))
  (load-stack-tn y x))

(define-move-fun (load-number-stack 5) (vop x y)
  ((character-stack) (character-reg)
   (sap-stack) (sap-reg)
   (signed-stack) (signed-reg)
   (unsigned-stack) (unsigned-reg))
  (load-frame-word y (current-nfp-tn vop) (tn-offset x)))

(define-move-fun (store-stack 5) (vop x y)
  ((any-reg descriptor-reg) (control-stack))
  (store-stack-tn y x))

(define-move-fun (store-number-stack 5) (vop x y)
  ((character-reg) (character-stack)
   (sap-reg) (sap-stack)
   (signed-reg) (signed-stack)
   (unsigned-reg) (unsigned-stack))
  (store-frame-word x (current-nfp-tn vop) (tn-offset y)))

;;;; The Move VOP:

(define-vop (move)
  (:args (x :target y
            :scs (any-reg descriptor-reg)
            :load-if (not (location= x y))))
  (:results (y :scs (any-reg descriptor-reg control-stack)
               :load-if (not (location= x y))))
  (:generator 0
    (unless (location= x y)
      (sc-case y
        ((any-reg descriptor-reg)
         (move y x))
        (control-stack
         (store-stack-tn y x))))))

(define-move-vop move :move
  (any-reg descriptor-reg)
  (any-reg descriptor-reg))

;;; The Move-Argument VOP is used for moving descriptor values into
;;; another frame for argument or known value passing. FP is the frame
;;; pointer of the callee frame.
(define-vop (move-arg)
  (:args (x :target y
            :scs (any-reg descriptor-reg))
         (fp :scs (any-reg)
             :load-if (not (sc-is y any-reg descriptor-reg))))
  (:results (y))
  (:generator 0
    (sc-case y
      ((any-reg descriptor-reg)
       (move y x))
      (control-stack
       (store-frame-word x fp (tn-offset y))))))

(define-move-vop move-arg :move-arg
  (any-reg descriptor-reg)
  (any-reg descriptor-reg))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (word-move)
  (:args (x :scs (signed-reg unsigned-reg) :load-if (not (location= x y))))
  (:results (y :scs (signed-reg unsigned-reg) :load-if (not (location= x y))))
  (:note "word integer move")
  
  (:generator 0 (vop-not-yet-implemented 'word-move x y)))

(define-vop (move-from-word/fixnum)
  (:args (x :scs (signed-reg unsigned-reg)))
  (:results (y :scs (any-reg descriptor-reg)))
  (:result-types (:or positive-fixnum fixnum))
  (:note "fixnum tagging")
  (:generator 1 (vop-not-yet-implemented 'move-from-word/fixnum x y)))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (move-to-word/fixnum)
  (:args (x :scs (any-reg descriptor-reg)))
  (:results (y :scs (signed-reg unsigned-reg)))
  (:arg-types (:or positive-fixnum fixnum))
  (:note "fixnum untagging")
  (:generator 1 (vop-not-yet-implemented 'move-to-word/fixnum x y)))

(define-vop (move-to-word-c)
  (:args (x :scs (constant)))
  (:results (y :scs (signed-reg unsigned-reg)))
  (:note "constant load")
  (:vop-var vop)
  (:generator 1 (vop-not-yet-implemented 'move-to-word-c x y)))

(define-vop (move-to-word/integer)
  (:args (x :scs (descriptor-reg)))
  (:results (y :scs (signed-reg unsigned-reg)))
  (:note "integer to untagged word coercion")
  (:generator 3 (vop-not-yet-implemented 'move-to-word/integer x y)))

(define-vop (move-from-signed)
  (:args (arg :scs (signed-reg unsigned-reg)))
  (:results (y :scs (any-reg descriptor-reg)))
  (:note "signed word to integer coercion")
  (:generator 15 (vop-not-yet-implemented 'move-from-signed arg y)))

(define-vop (move-from-fixnum+/-1)
  (:args (x :scs (signed-reg unsigned-reg)))
  (:results (y :scs (any-reg descriptor-reg)))
  (:variant-vars constant)
  (:variant nil)
  (:vop-var vop)
  (:generator 4 (vop-not-yet-implemented 'move-from-fixnum+/-1 x y constant)))

(define-vop (move-from-fixnum+1)
  (:args (x :scs (signed-reg unsigned-reg)))
  (:results (y :scs (any-reg descriptor-reg)))
  (:variant-vars constant)
  (:variant (1+ most-positive-fixnum))
  (:vop-var vop)
  (:generator 4 (vop-not-yet-implemented 'move-from-fixnum+1 x y constant)))

(define-vop (move-from-fixnum-1)
  (:args (x :scs (signed-reg unsigned-reg)))
  (:results (y :scs (any-reg descriptor-reg)))
  (:variant-vars constant)
  (:variant (1- most-negative-fixnum))
  (:vop-var vop)
  (:generator 4 (vop-not-yet-implemented 'move-from-fixnum-1 x y constant)))

(define-vop (move-from-unsigned)
  (:args (arg :scs (signed-reg unsigned-reg)))
  (:results (y :scs (any-reg descriptor-reg)))
  (:note "unsigned word to integer coercion")
  (:generator 20 (vop-not-yet-implemented 'move-from-unsigned arg y)))

(define-vop (move-word-arg)
  (:args (x :scs (signed-reg unsigned-reg))
   (fp :scs (any-reg) :load-if (not (sc-is y signed-reg unsigned-reg))))
  (:results (y))
  (:note "word integer argument move")
  (:generator 0 (vop-not-yet-implemented 'move-word-arg x fp y)))
