;;;; the WebAssembly definitions of VOPs used for non-local exit (throw,
;;;; lexical exit, etc.)

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.
;;;;
;;;; This software is derived from the CMU CL system, which was
;;;; written at Carnegie Mellon University and released into the
;;;; public domain. The software is in the public domain and is
;;;; provided with absolutely no warranty. See the COPYING and CREDITS
;;;; files for more information.

(in-package "SB-VM")

;;; Make a TN for the argument count passing location for a
;;; non-local entry.
(defun make-nlx-entry-arg-start-location ()
  (make-wired-tn *fixnum-primitive-type* any-reg-sc-number ocfp-offset))

;;; Save and restore dynamic environment.
;;;
;;; These VOPs are used in the reentered function to restore the appropriate
;;; dynamic environment. Currently we only save the Current-Catch and binding
;;; stack pointer. We don't need to save/restore the current unwind-protect,
;;; since unwind-protects are implicitly processed during unwinding.

(define-vop (save-dynamic-state)
  (:results (catch :scs (descriptor-reg))
            (nfp :scs (descriptor-reg))
            (nsp :scs (descriptor-reg)))
  (:vop-var vop)
  (:generator 13
    (load-current-catch-block catch)
    (let ((cur-nfp (current-nfp-tn vop)))
      (when cur-nfp
        (move nfp cur-nfp)))
    (move nsp nsp-tn)))

(define-vop (restore-dynamic-state)
  (:args (catch :scs (descriptor-reg))
         (nfp :scs (descriptor-reg))
         (nsp :scs (descriptor-reg)))
  (:vop-var vop)
  (:generator 10
    (store-current-catch-block catch)
    (let ((cur-nfp (current-nfp-tn vop)))
      (when cur-nfp
        (move cur-nfp nfp)))
    (move nsp-tn nsp)))

(define-vop (current-stack-pointer)
  (:results (res :scs (any-reg descriptor-reg)))
  (:generator 1
    (move res csp-tn)))

(define-vop (current-binding-pointer)
  (:results (res :scs (any-reg descriptor-reg)))
  (:generator 1
    (load-binding-stack-pointer res)))

(define-vop (current-nsp)
  (:results (res :scs (any-reg descriptor-reg)))
  (:generator 1
    (move res nsp-tn)))

(define-vop (set-nsp)
  (:args (nsp :scs (any-reg descriptor-reg)))
  (:generator 1
    (move nsp-tn nsp)))

;;; The catch/unwind blocks and the NLX entry points are built on Wasm
;;; exception handling; they are written in Sprint 3 (see
;;; doc/wasm-port/02-design.md, 2.6).

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (%catch-breakup)
  (:args (current-block))
  (:policy :fast-safe)
  (:generator 17 (vop-not-yet-implemented '%catch-breakup current-block)))

(define-vop (%unwind-protect-breakup)
  (:args (current-block))
  (:policy :fast-safe)
  (:generator 17 (vop-not-yet-implemented '%unwind-protect-breakup current-block)))

(define-vop (make-catch-block)
  (:args (tn) (tag :scs (any-reg descriptor-reg)))
  (:results (block :scs (any-reg)))
  (:info entry-label)
  (:generator 44 (vop-not-yet-implemented 'make-catch-block tn tag block entry-label)))

(define-vop (make-unwind-block)
  (:args (tn))
  (:results (block :scs (any-reg)))
  (:info entry-label)
  (:generator 22 (vop-not-yet-implemented 'make-unwind-block tn block entry-label)))

(define-vop (nlx-entry)
  (:args (sp) (start) (count))
  (:results (values :load-if nil :more t))
  (:info label nvals)
  (:save-p :force-to-stack)
  (:vop-var vop)
  (:generator 30 (vop-not-yet-implemented 'nlx-entry sp start count values label nvals)))

(define-vop (nlx-entry-multiple)
  (:args (top) (src) (count))
  (:results (result :scs (any-reg)) (num :scs (any-reg)))
  (:info label)
  (:save-p :force-to-stack)
  (:vop-var vop)
  (:generator 30 (vop-not-yet-implemented 'nlx-entry-multiple top src count result num label)))

(define-vop (nlx-entry-single)
  (:args (sp) (value))
  (:results (res))
  (:info label)
  (:save-p :force-to-stack)
  (:vop-var vop)
  (:generator 30 (vop-not-yet-implemented 'nlx-entry-single sp value res label)))

(define-vop (set-unwind-protect)
  (:args (uwp :scs (any-reg)))
  (:generator 7 (vop-not-yet-implemented 'set-unwind-protect uwp)))

(define-vop (uwp-entry)
  (:args)
  (:results (block) (start) (count))
  (:info label)
  (:save-p :force-to-stack)
  (:vop-var vop)
  (:generator 0 (vop-not-yet-implemented 'uwp-entry block start count label)))
