;;;; pred VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (branch)
  (:args)
  (:info dest)
  (:generator 3 (vop-not-yet-implemented 'branch dest)))

(define-vop (branch-if)
  (:args)
  (:info dest flags not-p)
  (:generator 0 (vop-not-yet-implemented 'branch-if dest flags not-p)))

(define-vop (if-eq)
  (:args (x :scs (any-reg descriptor-reg)) (y :scs (any-reg descriptor-reg)))
  (:result-types)
  (:info target not-p)
  (:conditional)
  (:translate eq)
  (:policy :fast-safe)
  (:generator 3 (vop-not-yet-implemented 'if-eq x y target not-p)))

;;; No conditional-move conversion: the engine does that.
(defun convert-conditional-move-p (dst-tn)
  (declare (ignore dst-tn))
  nil)
