;;;; show VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (print)
  (:args (object :scs (descriptor-reg any-reg)))
  (:results (result :scs (descriptor-reg)))
  (:save-p t)
  (:vop-var vop)
  (:generator 100 (vop-not-yet-implemented 'print object result)))
