;;;; system VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;; Pending interrupts are polled (doc/wasm-port/02-design.md, 2.7); this is
;;; the function the poll calls when the flag is set.
(defknown sb-unix::receive-pending-interrupt () (values))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (sb-c::mark-covered)
  (:args)
  (:info index)
  (:generator 4 (vop-not-yet-implemented 'sb-c::mark-covered index)))

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (%sqrtf)
  (:args (x :scs (single-reg)))
  (:results (y :scs (single-reg)))
  (:arg-types (:or single-float))
  (:result-types (:or single-float))
  (:translate %sqrtf)
  (:policy :fast-safe)
  (:save-p :compute-only)
  (:note "inline float arithmetic")
  (:generator 1 (vop-not-yet-implemented '%sqrtf x y)))

(define-vop (%sqrt)
  (:args (x :scs (double-reg)))
  (:results (y :scs (double-reg)))
  (:arg-types (:or double-float))
  (:result-types (:or double-float))
  (:translate %sqrt)
  (:policy :fast-safe)
  (:save-p :compute-only)
  (:note "inline float arithmetic")
  (:generator 1 (vop-not-yet-implemented '%sqrt x y)))

(define-vop (descriptor-hash32)
  (:args (arg :scs (any-reg descriptor-reg)))
  (:results (res :scs (any-reg)))
  (:result-types (:or positive-fixnum))
  (:translate descriptor-hash32)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'descriptor-hash32 arg res)))

(define-vop (widetag-of)
  (:args (object :scs (descriptor-reg)))
  (:results (result :scs (unsigned-reg)))
  (:result-types (:or positive-fixnum))
  (:translate widetag-of)
  (:policy :fast-safe)
  (:generator 6 (vop-not-yet-implemented 'widetag-of object result)))

(define-vop (sb-c::%structure-is-a)
  (:args (x :scs (descriptor-reg)))
  (:arg-types * (:constant t))
  (:result-types)
  (:info target not-p test-layout)
  (:conditional)
  (:translate sb-c::%structure-is-a)
  (:policy :fast-safe)
  (:generator 4 (vop-not-yet-implemented 'sb-c::%structure-is-a x target not-p test-layout)))

(define-vop (%other-pointer-widetag)
  (:args (object :scs (descriptor-reg)))
  (:results (result :scs (unsigned-reg)))
  (:result-types (:or positive-fixnum))
  (:translate %other-pointer-widetag)
  (:policy :fast-safe)
  (:generator 6 (vop-not-yet-implemented '%other-pointer-widetag object result)))

(define-vop (%fun-pointer-widetag)
  (:args (function :scs (descriptor-reg)))
  (:results (result :scs (unsigned-reg)))
  (:result-types (:or positive-fixnum))
  (:translate %fun-pointer-widetag)
  (:policy :fast-safe)
  (:generator 6 (vop-not-yet-implemented '%fun-pointer-widetag function result)))

(define-vop (get-header-data)
  (:args (x :scs (descriptor-reg)))
  (:results (res :scs (unsigned-reg)))
  (:result-types (:or positive-fixnum))
  (:translate get-header-data)
  (:policy :fast-safe)
  (:generator 6 (vop-not-yet-implemented 'get-header-data x res)))

(define-vop (set-header-data)
  (:args (x :scs (descriptor-reg)) (data :scs (any-reg immediate)))
  (:arg-types * (:or positive-fixnum))
  (:translate set-header-data)
  (:policy :fast-safe)
  (:generator 6 (vop-not-yet-implemented 'set-header-data x data)))

(define-vop (binding-stack-pointer-sap)
  (:args)
  (:results (int :scs (sap-reg)))
  (:result-types (:or system-area-pointer))
  (:translate binding-stack-pointer-sap)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'binding-stack-pointer-sap int)))

(define-vop (control-stack-pointer-sap)
  (:args)
  (:results (int :scs (sap-reg)))
  (:result-types (:or system-area-pointer))
  (:translate control-stack-pointer-sap)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'control-stack-pointer-sap int)))

(define-vop (code-instructions)
  (:args (code :scs (descriptor-reg)))
  (:results (sap :scs (sap-reg)))
  (:result-types (:or system-area-pointer))
  (:translate code-instructions)
  (:policy :fast-safe)
  (:generator 10 (vop-not-yet-implemented 'code-instructions code sap)))

(define-vop (code-trailer-ref)
  (:args (code :scs (descriptor-reg)) (offset :scs (signed-reg)))
  (:results (res :scs (unsigned-reg)))
  (:arg-types * (:or fixnum))
  (:result-types (:or unsigned-byte-32 unsigned-byte-31 positive-fixnum))
  (:translate code-trailer-ref)
  (:policy :fast-safe)
  (:generator 10 (vop-not-yet-implemented 'code-trailer-ref code offset res)))

(define-vop (compute-fun)
  (:args (code :scs (descriptor-reg)) (offset :scs (signed-reg unsigned-reg)))
  (:results (func :scs (descriptor-reg)))
  (:arg-types * (:or positive-fixnum))
  (:generator 10 (vop-not-yet-implemented 'compute-fun code offset func)))

(define-vop (sb-unix::receive-pending-interrupt)
  (:args)
  (:translate sb-unix::receive-pending-interrupt)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'sb-unix::receive-pending-interrupt )))

(define-vop (halt)
  (:args)
  (:generator 1 (vop-not-yet-implemented 'halt )))

(define-vop (spin-loop-hint)
  (:args)
  (:translate spin-loop-hint)
  (:policy :fast-safe)
  (:generator 0 (vop-not-yet-implemented 'spin-loop-hint )))

(define-vop (%compiler-barrier)
  (:args)
  (:translate %compiler-barrier)
  (:policy :fast-safe)
  (:generator 3 (vop-not-yet-implemented '%compiler-barrier )))

(define-vop (%memory-barrier)
  (:args)
  (:translate %memory-barrier)
  (:policy :fast-safe)
  (:generator 3 (vop-not-yet-implemented '%memory-barrier )))

(define-vop (%read-barrier)
  (:args)
  (:translate %read-barrier)
  (:policy :fast-safe)
  (:generator 3 (vop-not-yet-implemented '%read-barrier )))

(define-vop (%write-barrier)
  (:args)
  (:translate %write-barrier)
  (:policy :fast-safe)
  (:generator 3 (vop-not-yet-implemented '%write-barrier )))

(define-vop (%data-dependency-barrier)
  (:args)
  (:translate %data-dependency-barrier)
  (:policy :fast-safe)
  (:generator 3 (vop-not-yet-implemented '%data-dependency-barrier )))



(define-vop (do-pending-interrupt)
  (:args)
  (:vop-var #:vop)
  (:generator 247 (vop-not-yet-implemented 'do-pending-interrupt )))


(define-vop (current-sp)
  (:args)
  (:results (res :scs (sap-reg)))
  (:result-types (:or system-area-pointer))
  (:translate current-sp)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented 'current-sp res)))

(define-vop (stack-ref)
  (:args (object :scs (sap-reg)) (offset :scs (any-reg)))
  (:results (result :scs (descriptor-reg)))
  (:arg-types (:or system-area-pointer) (:or positive-fixnum))
  (:result-types *)
  (:translate stack-ref)
  (:policy :fast-safe)
  (:generator 5 (vop-not-yet-implemented 'stack-ref object offset result)))

(define-vop (%set-stack-ref)
  (:args (object :scs (sap-reg)) (offset :scs (any-reg))
   (value :scs (descriptor-reg)))
  (:arg-types (:or system-area-pointer) (:or positive-fixnum) *)
  (:translate %set-stack-ref)
  (:policy :fast-safe)
  (:generator 2 (vop-not-yet-implemented '%set-stack-ref object offset value)))

(define-vop (code-header-ref)
  (:args (object :scs (descriptor-reg)) (index :scs (any-reg)))
  (:results (value :scs (descriptor-reg any-reg)))
  (:arg-types * (:or positive-fixnum fixnum))
  (:result-types *)
  (:translate code-header-ref)
  (:policy :fast-safe)
  (:generator 5 (vop-not-yet-implemented 'code-header-ref object index value)))

(define-vop (code-header-ref-c)
  (:args (object :scs (descriptor-reg)))
  (:results (value :scs (descriptor-reg any-reg)))
  (:arg-types * (:constant (load/store-index 4 7 0)))
  (:result-types *)
  (:info index)
  (:translate code-header-ref)
  (:policy :fast-safe)
  (:generator 4 (vop-not-yet-implemented 'code-header-ref-c object value index)))

(define-vop (%weakvec-ref)
  (:args (object :scs (descriptor-reg)) (index :scs (any-reg)))
  (:results (value :scs (any-reg descriptor-reg)))
  (:arg-types * (:or positive-fixnum fixnum))
  (:result-types *)
  (:translate %weakvec-ref)
  (:policy :fast-safe)
  (:generator 5 (vop-not-yet-implemented '%weakvec-ref object index value)))

(define-vop (%weakvec-ref-c)
  (:args (object :scs (descriptor-reg)))
  (:results (value :scs (any-reg descriptor-reg)))
  (:arg-types * (:constant (load/store-index 4 7 2)))
  (:result-types *)
  (:info index)
  (:translate %weakvec-ref)
  (:policy :fast-safe)
  (:generator 4 (vop-not-yet-implemented '%weakvec-ref-c object value index)))

(define-vop (%weakvec-set)
  (:args (object :scs (descriptor-reg)) (index :scs (any-reg))
   (value :scs (any-reg descriptor-reg)))
  (:arg-types * (:or positive-fixnum fixnum) *)
  (:translate %weakvec-set)
  (:policy :fast-safe)
  (:generator 3 (vop-not-yet-implemented '%weakvec-set object index value)))

(define-vop (%weakvec-set-c)
  (:args (object :scs (descriptor-reg)) (value :scs (any-reg descriptor-reg)))
  (:arg-types * (:constant (load/store-index 4 7 2)) *)
  (:info index)
  (:translate %weakvec-set)
  (:policy :fast-safe)
  (:generator 1 (vop-not-yet-implemented '%weakvec-set-c object value index)))



