;;;; type-vops VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

;;;; List/symbol types:
;;;
;;; symbolp (or symbol (eq nil))
;;; consp (and list (not (eq nil)))

(define-vop (symbolp type-predicate)
  (:translate symbolp)
  (:generator 12
    (load-reg value)
    (inst i32.const nil-value)
    (inst i32.eq)
    (inst jump-if (if not-p drop-thru target))
    (test-type value temp target not-p (symbol-widetag))
    DROP-THRU))

(define-vop (consp type-predicate)
  (:translate consp)
  (:generator 8
    (load-reg value)
    (inst i32.const nil-value)
    (inst i32.eq)
    (inst jump-if (if not-p target drop-thru))
    (test-type value temp target not-p (list-pointer-lowtag))
    DROP-THRU))

;;;; Type tests. The value is in a register; the test pushes an i32 and
;;;; branches with JUMP-IF. TEMP is unused: the operand stack is the
;;;; temporary.

(defun %test-fixnum (value temp target not-p)
  (declare (ignore temp))
  (assemble ()
    (load-reg value)
    (inst i32.const fixnum-tag-mask)
    (inst i32.and)
    (unless not-p (inst i32.eqz))
    (inst jump-if target)))

(defun %test-immediate (value temp target not-p immediate &key value-tn-ref)
  (declare (ignore temp value-tn-ref))
  (assemble ()
    (load-reg value)
    (inst i32.const widetag-mask)
    (inst i32.and)
    (inst i32.const immediate)
    (if not-p (inst i32.ne) (inst i32.eq))
    (inst jump-if target)))

(defun %test-lowtag (value temp target not-p lowtag &key value-tn-ref)
  (declare (ignore temp value-tn-ref))
  (assemble ()
    (load-reg value)
    (inst i32.const lowtag-mask)
    (inst i32.and)
    (inst i32.const lowtag)
    (if not-p (inst i32.ne) (inst i32.eq))
    (inst jump-if target)))

;;; Header (widetag) tests. HEADERS is a canonicalized list of widetags
;;; and (start . end) ranges. The lowtag is checked first unless the
;;; compiler already knows the value is an other pointer; then the header
;;; byte is loaded into the scratch register and compared against every
;;; entry, each comparison a separate JUMP-IF at an empty-stack point.
(defun %test-headers (value temp target not-p function-p headers
                      &key (drop-through (gen-label)) value-tn-ref immediate-tested)
  (declare (ignore temp))
  (let ((lowtag (if function-p fun-pointer-lowtag other-pointer-lowtag)))
    (multiple-value-bind (when-true when-false)
        ;; WHEN-TRUE and WHEN-FALSE are the labels to branch to when
        ;; we know it's true and when we know it's false respectively.
        (if not-p
            (values drop-through target)
            (values target drop-through))
      (assemble ()
        (unless (and value-tn-ref
                     (eq lowtag other-pointer-lowtag)
                     (other-pointer-tn-ref-p value-tn-ref nil immediate-tested))
          (%test-lowtag value nil when-false t lowtag))
        ;; tmp = widetag byte of the header
        (store-reg tmp-tn
          (load-reg value)
          (emit-load-sized 1 nil (- lowtag)))
        (do ((remaining headers (cdr remaining)))
            ((null remaining))
          (let ((header (car remaining))
                (last (null (cdr remaining))))
            (cond
              ((atom header)
               (load-reg tmp-tn)
               (inst i32.const header)
               (cond (last
                      (if not-p (inst i32.ne) (inst i32.eq))
                      (inst jump-if target))
                     (t
                      (inst i32.eq)
                      (inst jump-if when-true))))
              (t
               (let ((start (car header))
                     (end (cdr header)))
                 (unless (= start bignum-widetag)
                   (load-reg tmp-tn)
                   (inst i32.const start)
                   (inst i32.lt_u)
                   (inst jump-if when-false))
                 (load-reg tmp-tn)
                 (inst i32.const end)
                 (cond (last
                        (if not-p (inst i32.gt_u) (inst i32.le_u))
                        (inst jump-if target))
                       (t
                        (inst i32.le_u)
                        (inst jump-if when-true))))))))
        (emit-label drop-through)))))

(defun %test-fixnum-and-headers (value temp target not-p headers
                                 &key value-tn-ref immediate-tested)
  (let ((drop-through (gen-label)))
    (assemble ()
      (load-reg value)
      (inst i32.const fixnum-tag-mask)
      (inst i32.and)
      (inst i32.eqz)
      (inst jump-if (if not-p drop-through target)))
    (%test-headers value temp target not-p nil headers
                   :drop-through drop-through
                   :value-tn-ref value-tn-ref
                   :immediate-tested immediate-tested)))

;;;; Other integer ranges.

;;; A (SIGNED-BYTE 32) is either a fixnum or a bignum with exactly one
;;; digit; the whole header word is compared, which also checks the
;;; widetag.
(defun signed-byte-n-word-bits-test (value not-p target not-target)
  (multiple-value-bind (yep nope)
      (if not-p
          (values not-target target)
          (values target not-target))
    (assemble ()
      (load-reg value)
      (inst i32.const fixnum-tag-mask)
      (inst i32.and)
      (inst i32.eqz)
      (inst jump-if yep)
      (%test-lowtag value nil nope t other-pointer-lowtag)
      (load-reg value)
      (emit-load-word (- other-pointer-lowtag))
      (inst i32.const (+ (ash 1 n-widetag-bits) bignum-widetag))
      (if not-p (inst i32.ne) (inst i32.eq))
      (inst jump-if target)))
  (values))

(define-vop (signed-byte-32-p type-predicate)
  (:translate signed-byte-32-p)
  (:ignore temp)
  (:generator 10
    (let ((not-target (gen-label)))
      (signed-byte-n-word-bits-test value not-p target not-target)
      (emit-label not-target))))

;;; An (UNSIGNED-BYTE 32) is a positive fixnum, a bignum with exactly one
;;; positive digit, or a bignum with exactly two digits whose second digit
;;; is zero.
(define-vop (unsigned-byte-32-p type-predicate)
  (:translate unsigned-byte-32-p)
  (:ignore temp)
  (:generator 10
    (let ((not-target (gen-label))
          (single-word (gen-label))
          (fixnum (gen-label)))
      (multiple-value-bind (yep nope)
          (if not-p
              (values not-target target)
              (values target not-target))
        (assemble ()
          ;; Is it a fixnum? Then the value itself carries the sign.
          (store-reg tmp-tn (load-reg value))
          (load-reg value)
          (inst i32.const fixnum-tag-mask)
          (inst i32.and)
          (inst i32.eqz)
          (inst jump-if fixnum)
          ;; If not, is it an other pointer?
          (%test-lowtag value nil nope t other-pointer-lowtag)
          ;; Get the header. Is it a one-digit bignum?
          (store-reg tmp-tn
            (load-reg value)
            (emit-load-word (- other-pointer-lowtag)))
          (load-reg tmp-tn)
          (inst i32.const (+ (ash 1 n-widetag-bits) bignum-widetag))
          (inst i32.eq)
          (inst jump-if single-word)
          ;; If it's other than two digits, it can't be an (unsigned-byte 32)
          (load-reg tmp-tn)
          (inst i32.const (+ (ash 2 n-widetag-bits) bignum-widetag))
          (inst i32.ne)
          (inst jump-if nope)
          ;; The second digit must be all zeros.
          (load-reg value)
          (emit-load-word (- (ash (1+ bignum-digits-offset) word-shift) other-pointer-lowtag))
          (inst i32.eqz)
          (inst jump-if yep)
          (inst jump nope)

          (emit-label single-word)
          ;; Get the single digit.
          (store-reg tmp-tn
            (load-reg value)
            (emit-load-word (- (ash bignum-digits-offset word-shift) other-pointer-lowtag)))

          ;; positive implies (unsigned-byte 32).
          (emit-label fixnum)
          (load-reg tmp-tn)
          (inst i32.const 0)
          (if not-p (inst i32.lt_s) (inst i32.ge_s))
          (inst jump-if target)))
      (emit-label not-target))))
