;;;; type-vops VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (symbolp)
  (:args (value :scs (any-reg descriptor-reg)))
  (:result-types)
  (:info target not-p)
  (:conditional)
  (:translate symbolp)
  (:policy :fast-safe)
  (:generator 12 (vop-not-yet-implemented 'symbolp value target not-p)))

(define-vop (consp)
  (:args (value :scs (any-reg descriptor-reg)))
  (:result-types)
  (:info target not-p)
  (:conditional)
  (:translate consp)
  (:policy :fast-safe)
  (:generator 8 (vop-not-yet-implemented 'consp value target not-p)))






;;;; Type tests. The value is in a register; the test pushes an i32 and
;;;; branches with JUMP-IF. TEMP is unused: the operand stack is the
;;;; temporary.

(defun %test-fixnum (value temp target not-p)
  (declare (ignore temp))
  (assemble ()
    (load-reg value)
    (inst i32.const fixnum-tag-mask)
    (inst i32.and)
    (unless not-p (inst i32.eqz))
    (inst jump-if target)))

(defun %test-immediate (value temp target not-p immediate &key value-tn-ref)
  (declare (ignore temp value-tn-ref))
  (assemble ()
    (load-reg value)
    (inst i32.const widetag-mask)
    (inst i32.and)
    (inst i32.const immediate)
    (if not-p (inst i32.ne) (inst i32.eq))
    (inst jump-if target)))

(defun %test-lowtag (value temp target not-p lowtag &key value-tn-ref)
  (declare (ignore temp value-tn-ref))
  (assemble ()
    (load-reg value)
    (inst i32.const lowtag-mask)
    (inst i32.and)
    (inst i32.const lowtag)
    (if not-p (inst i32.ne) (inst i32.eq))
    (inst jump-if target)))

;;; Header (widetag) tests need the other-pointer check, the header load
;;; and range tests; written in Sprint 3.
(defun %test-headers (value temp target not-p function-p headers
                      &key drop-through value-tn-ref immediate-tested)
  (declare (ignore value temp target not-p function-p headers
                   drop-through value-tn-ref immediate-tested))
  (vop-not-yet-implemented '%test-headers))

(defun %test-fixnum-and-headers (value temp target not-p headers
                                 &key value-tn-ref immediate-tested)
  (let ((drop-through (gen-label)))
    (assemble ()
      (load-reg value)
      (inst i32.const fixnum-tag-mask)
      (inst i32.and)
      (inst i32.eqz)
      (inst jump-if (if not-p drop-through target)))
    (%test-headers value temp target not-p nil headers
                   :drop-through drop-through
                   :value-tn-ref value-tn-ref
                   :immediate-tested immediate-tested)))
