;;;; values VOPs for the WebAssembly target.
;;;;
;;;; Sprint 2 placeholder: the VOPs are written in the next sprint (see
;;;; doc/wasm-port/04-sprints.md). The file exists so that the backend
;;;; builds.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(in-package "SB-VM")

;;;; Skeletons: operand shapes taken from the riscv backend, generators to
;;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.

(define-vop (%%nip-values)
  (:args (last-nipped-ptr :scs (any-reg))
   (last-preserved-ptr :scs (any-reg))
   (moved-ptrs :scs (any-reg) :load-if nil :more t))
  (:results (r-moved-ptrs :scs (any-reg) :load-if nil :more t))
  (:generator 1 (vop-not-yet-implemented '%%nip-values last-nipped-ptr last-preserved-ptr moved-ptrs r-moved-ptrs)))

(define-vop (%more-arg-values)
  (:args (context :scs (descriptor-reg any-reg))
   (num :scs (any-reg)))
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:arg-types * (:or positive-fixnum))
  (:generator 20 (vop-not-yet-implemented '%more-arg-values context num start count)))

(define-vop (push-values)
  (:args (vals :scs (descriptor-reg any-reg control-stack) :load-if nil :more t))
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:info nvals)
  (:policy :fast-safe)
  (:generator 20 (vop-not-yet-implemented 'push-values vals start count nvals)))

(define-vop (reset-stack-pointer)
  (:args (ptr :scs (any-reg)))
  (:generator 1 (vop-not-yet-implemented 'reset-stack-pointer ptr)))

(define-vop (values-list)
  (:args (arg :scs (descriptor-reg)))
  (:results (start :scs (any-reg)) (count :scs (any-reg)))
  (:arg-types (:or list))
  (:policy :fast-safe)
  (:save-p :compute-only)
  (:vop-var vop)
  (:generator 0 (vop-not-yet-implemented 'values-list arg start count)))
