;;;; Differential test cases for the WebAssembly backend, level 1.
;;;; (name lambda-list body args-list...) — each args-list is one case.
;;;;
;;;; Arguments and results are raw register words, so only fixnums,
;;;; characters, T and NIL cross the boundary. The functions must not need
;;;; full calls (the call convention is a later sprint): everything they do
;;;; is open-coded, with type declarations narrow enough that the compiler
;;;; picks the inline VOPs. Error paths (type checks, division by zero) are
;;;; traps into the runtime, which is fine.
(
 ;; constants and arguments
 ("const-42" () ((declare (optimize (safety 0))) 42) ())
 ("identity-fixnum" (a) ((declare (fixnum a)) a) (7) (-7) (0))
 ("first-of-two" (a b) ((declare (fixnum a b)) (progn b a)) (1 2))
 ("second-of-two" (a b) ((declare (fixnum a b)) (progn a b)) (1 2))
 ("const-char" () (#\A) ())
 ("const-nil" () (nil) ())
 ("const-t" () (t) ())
 ("const-big-fixnum" () (123456789) ())
 ("const-negative" () (-100000) ())

 ;; fixnum arithmetic
 ("add" (a b) ((declare (fixnum a b)) (the fixnum (+ a b))) (1 2) (-5 3) (100000 200000))
 ("sub" (a b) ((declare (fixnum a b)) (the fixnum (- a b))) (1 2) (-5 3) (300000 200000))
 ("add-c" (a) ((declare (fixnum a)) (the fixnum (+ a 10))) (1) (-20))
 ("sub-c" (a) ((declare (fixnum a)) (the fixnum (- a 10))) (1) (-20))
 ("one-plus" (a) ((declare (fixnum a)) (the fixnum (1+ a))) (41) (-1))
 ("one-minus" (a) ((declare (fixnum a)) (the fixnum (1- a))) (43) (0))
 ("negate" (a) ((declare (fixnum a)) (the fixnum (- a))) (5) (-5) (0))
 ("mul" (a b) ((declare (type (signed-byte 14) a b)) (* a b)) (6 7) (-3 4) (0 9) (-100 -100))
 ("mul-c" (a) ((declare (type (signed-byte 20) a)) (* a 12)) (6) (-3))
 ("truncate-q" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (values (truncate a b)))
  (17 5) (-17 5) (100 10))
 ("truncate-r" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (nth-value 1 (truncate a b)))
  (17 5) (-17 5) (100 10))
 ("rem" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (rem a b)) (17 5) (-17 5))
 ("mod" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (mod a b)) (17 5) (-17 5))
 ("floor-q" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (values (floor a b))) (17 5) (-17 5))
 ("abs" (a) ((declare (type (signed-byte 20) a)) (abs a)) (5) (-5) (0))
 ("max" (a b) ((declare (fixnum a b)) (max a b)) (1 2) (2 1) (-3 -4))
 ("min" (a b) ((declare (fixnum a b)) (min a b)) (1 2) (2 1) (-3 -4))
 ("mv-bind-truncate" (a b) ((declare (fixnum a) (type (integer 1 1000) b))
                            (multiple-value-bind (q r) (truncate a b) (the fixnum (+ q r))))
  (17 5) (-17 5))

 ;; logical operations and shifts
 ("logand" (a b) ((declare (fixnum a b)) (logand a b)) (12 10) (-1 255) (0 7))
 ("logior" (a b) ((declare (fixnum a b)) (logior a b)) (12 10) (-8 3) (0 7))
 ("logxor" (a b) ((declare (fixnum a b)) (logxor a b)) (12 10) (-1 255) (5 5))
 ("lognot" (a) ((declare (fixnum a)) (lognot a)) (0) (5) (-6))
 ("logand-c" (a) ((declare (fixnum a)) (logand a 255)) (300) (-1) (0))
 ("logior-c" (a) ((declare (fixnum a)) (logior a 256)) (1) (256) (-1))
 ("logxor-c" (a) ((declare (fixnum a)) (logxor a 3)) (1) (0) (-1))
 ("logtest" (a b) ((declare (fixnum a b)) (logtest a b)) (12 4) (12 3))
 ("ash-left-c" (a) ((declare (type (signed-byte 16) a)) (ash a 3)) (5) (-5) (0))
 ("ash-right-c" (a) ((declare (fixnum a)) (ash a -3)) (40) (-40) (7))
 ("ash-left-var" (a b) ((declare (type (unsigned-byte 8) a) (type (integer 0 8) b)) (ash a b))
  (5 3) (255 8) (1 0))
 ("ash-right-var" (a b) ((declare (fixnum a) (type (integer -31 0) b)) (ash a b))
  (40 -3) (-40 -3) (7 0) (100 -31))
 ("ash-var-signed" (a b) ((declare (type (signed-byte 16) a) (type (integer -40 8) b)) (ash a b))
  (5 3) (-5 3) (40 -3) (-40 -3) (-40 -40) (12 -40))
 ("ldb" (a) ((declare (fixnum a)) (ldb (byte 8 4) a)) (4095) (-1) (16))
 ("integer-length" (a) ((declare (fixnum a)) (integer-length a)) (0) (1) (255) (256) (-1) (-256))
 ("logcount" (a) ((declare (type (unsigned-byte 29) a)) (logcount a)) (0) (255) (1023) (#x0AAAAAAA))
 ("evenp" (a) ((declare (fixnum a)) (evenp a)) (4) (5) (-2))
 ("oddp" (a) ((declare (fixnum a)) (oddp a)) (4) (5) (-3))

 ;; comparisons
 ("less" (a b) ((declare (fixnum a b)) (< a b)) (1 2) (2 1) (3 3) (-5 2))
 ("greater" (a b) ((declare (fixnum a b)) (> a b)) (1 2) (2 1) (3 3) (-5 2))
 ("less-equal" (a b) ((declare (fixnum a b)) (<= a b)) (1 2) (2 1) (3 3))
 ("greater-equal" (a b) ((declare (fixnum a b)) (>= a b)) (1 2) (2 1) (3 3))
 ("num-equal" (a b) ((declare (fixnum a b)) (= a b)) (1 2) (3 3) (-3 -3))
 ("num-not-equal" (a b) ((declare (fixnum a b)) (/= a b)) (1 2) (3 3))
 ("eql-fixnum" (a b) ((declare (fixnum a b)) (eql a b)) (1 2) (3 3))
 ("eq" (a b) ((eq a b)) (1 2) (3 3) (t t) (nil t))
 ("zerop" (a) ((declare (fixnum a)) (zerop a)) (0) (1) (-1))
 ("plusp" (a) ((declare (fixnum a)) (plusp a)) (0) (1) (-1))
 ("minusp" (a) ((declare (fixnum a)) (minusp a)) (0) (1) (-1))
 ("less-c" (a) ((declare (fixnum a)) (< a 100)) (99) (100) (101))
 ("in-range" (a) ((declare (fixnum a)) (typep a '(integer 0 10))) (-1) (0) (5) (10) (11))

 ;; control flow
 ("if-then-else" (a) ((if a 1 2)) (t) (nil) (5))
 ("not" (a) ((not a)) (t) (nil) (5))
 ("null" (a) ((null a)) (t) (nil) (5))
 ("and" (a b) ((and a b)) (t 5) (nil 5) (5 nil))
 ("or" (a b) ((or a b)) (t 5) (nil 5) (nil nil))
 ("cond-sign" (a) ((declare (fixnum a)) (cond ((< a 0) -1) ((> a 0) 1) (t 0))) (-7) (7) (0))
 ("when-unless" (a) ((declare (fixnum a)) (let ((r 0)) (declare (fixnum r))
                                              (when (> a 5) (setq r 1))
                                              (unless (> a 5) (setq r 2))
                                              r))
  (3) (9))
 ("sum-loop" (n) ((declare (type (integer 0 10000) n))
                  (let ((s 0)) (declare (type (integer 0 100000000) s))
                    (dotimes (i n) (setq s (+ s i)))
                    s))
  (0) (1) (10) (100))
 ("count-down" (n) ((declare (type (integer 0 10000) n))
                    (let ((c 0)) (declare (fixnum c))
                      (loop while (> n 0) do (setq n (1- n)) (setq c (the fixnum (+ c 2))))
                      c))
  (0) (5))
 ("fib-iter" (n) ((declare (type (integer 0 30) n))
                  (let ((a 0) (b 1)) (declare (type (integer 0 10000000) a b))
                    (dotimes (i n) (let ((c (+ a b))) (setq a b b c)))
                    a))
  (0) (1) (2) (10) (20))
 ("let-shadow" (a) ((declare (fixnum a)) (let ((a (the fixnum (+ a 1)))) (let ((a (the fixnum (* 2 a)))) a)))
  (5) (-1))
 ("flet-inline" (a b) ((declare (fixnum a b)) (flet ((sq+ (x y) (declare (fixnum x y)) (the fixnum (+ x y)))) (sq+ a b)))
  (3 4))

 ;; characters
 ("char-code" (c) ((char-code c)) (#\a) (#\Z) (#\Space))
 ("code-char" (n) ((declare (type (integer 0 255) n)) (code-char n)) (65) (97) (32))
 ("char=" (a b) ((char= a b)) (#\a #\a) (#\a #\b))
 ("char<" (a b) ((char< a b)) (#\a #\b) (#\b #\a) (#\a #\a))
 ("char>" (a b) ((char> a b)) (#\a #\b) (#\b #\a))
 ("char-roundtrip" (c) ((code-char (1+ (char-code c)))) (#\a) (#\A))
 ("characterp" (a) ((characterp a)) (#\a) (5) (nil) (t))

 ;; lists (allocation through the runtime)
 ("cons-car" (a b) ((car (cons a b))) (1 2) (t nil) (#\a 3))
 ("cons-cdr" (a b) ((cdr (cons a b))) (1 2) (t nil) (#\a 3))
 ("consp" (a) ((consp a)) (1) (nil) (t) (#\a))
 ("consp-cons" (a) ((consp (cons a a))) (1))
 ("listp" (a) ((listp a)) (1) (nil) (t))
 ("list-cadr" (a b c) ((cadr (list a b c))) (1 2 3) (nil t nil))
 ("list-sum" (a b c) ((declare (fixnum a b c))
                      (let ((l (list a b c)))
                        (the fixnum (+ (the fixnum (car l)) (the fixnum (cadr l)) (the fixnum (caddr l))))))
  (1 2 3) (10 -20 30))
 ("list-star" (a b) ((cdr (list* a b))) (1 2) (nil t))
 ("rplaca" (a b c) ((let ((x (cons a b))) (setf (car x) c) (car x))) (1 2 3))
 ("rplacd" (a b c) ((let ((x (cons a b))) (setf (cdr x) c) (cdr x))) (1 2 3))
 ("endp" (a) ((endp (list a))) (1))
 ("list-length-loop" (n) ((declare (type (integer 0 100) n))
                          (let ((l nil)) (dotimes (i n) (setq l (cons i l)))
                            (let ((c 0)) (declare (fixnum c))
                              (loop while l do (setq l (cdr l)) (incf c))
                              c)))
  (0) (3) (50))

 ;; symbols and type predicates
 ("symbolp" (a) ((symbolp a)) (t) (nil) (1) (#\a))
 ("integerp" (a) ((integerp a)) (1) (-1) (nil) (#\a) (t))
 ("numberp" (a) ((numberp a)) (1) (nil) (#\a))
 ("fixnump" (a) ((typep a 'fixnum)) (1) (nil) (#\a))
 ("stringp" (a) ((stringp a)) (1) (nil) (t))
 ("functionp" (a) ((functionp a)) (1) (nil) (t))
 ("vectorp" (a) ((vectorp a)) (1) (nil) (#\a))
 ("eq-t" (a) ((eq a t)) (t) (nil) (1))
 ("case-fixnum" (a) ((declare (fixnum a)) (case a (1 10) (2 20) ((3 4) 30) (t 0))) (1) (2) (3) (4) (5))

;;; Sprint 4: local calls, unknown values, non-local exit, dynamic extent,
;;; entry points with optional and rest arguments, floats. Still no full
;;; calls (no fdefns in the rig) and no boxed constants (no code header):
;;; float values are made from fixnum arguments with COERCE, ranges that
;;; TRUNCATE needs are derived or clamped with MIN/MAX of argument-derived
;;; values, and catch tags are fixnums or static symbols.

 ;; local calls: recursion keeps a LABELS function from being let-converted
 ("labels-sum-rec" (n) ((declare (type (integer 0 1000) n))
                        (labels ((sum (i) (declare (type (integer 0 1000) i))
                                   (if (= i 0) 0 (the fixnum (+ i (sum (1- i)))))))
                          (sum n)))
  (0) (1) (10) (100))
 ("labels-fib-rec" (n) ((declare (type (integer 0 20) n))
                        (labels ((fib (i) (declare (type (integer 0 20) i))
                                   (if (< i 2) i (the fixnum (+ (fib (- i 1)) (fib (- i 2)))))))
                          (fib n)))
  (0) (1) (2) (10) (15))
 ("labels-tail-loop" (n) ((declare (type (integer 0 10000) n))
                          (labels ((cnt (i acc) (declare (type (integer 0 10000) i) (fixnum acc))
                                     (if (= i 0) acc (cnt (1- i) (the fixnum (+ acc 2))))))
                            (cnt n 0)))
  (0) (5) (1000))
 ("flet-called-twice" (a b) ((declare (fixnum a b))
                             (flet ((twice (x) (declare (fixnum x)) (the fixnum (+ x x))))
                               (declare (notinline twice))
                               (the fixnum (- (twice a) (twice b)))))
  (3 4) (-10 10))
 ("labels-mutual" (n) ((declare (type (integer 0 100) n))
                       (labels ((ev (i) (declare (type (integer 0 100) i)) (if (= i 0) t (od (1- i))))
                                (od (i) (declare (type (integer 0 100) i)) (if (= i 0) nil (ev (1- i)))))
                         (ev n)))
  (0) (1) (7) (10))
 ("local-call-in-loop" (n) ((declare (type (integer 0 100) n))
                            (flet ((sq (x) (declare (type (integer 0 100) x)) (* x x)))
                              (declare (notinline sq))
                              (let ((s 0)) (declare (type (integer 0 1000000) s))
                                (dotimes (i n) (setq s (+ s (sq i))))
                                (the fixnum (+ s (sq n))))))
  (0) (3) (10))

 ;; multiple values through local calls
 ("mv-known-local" (a b) ((declare (fixnum a) (type (integer 1 100) b))
                          (labels ((divmod (x y) (declare (fixnum x) (type (integer 1 100) y))
                                     (truncate x y)))
                            (multiple-value-bind (q r) (divmod a b)
                              (multiple-value-bind (q2 r2) (divmod b 3)
                                (the fixnum (+ q r q2 r2))))))
  (17 5) (-17 5) (100 7))
 ("mv-unknown-local" (n) ((declare (fixnum n))
                          (labels ((f (x) (declare (fixnum x))
                                     (if (> x 0) (values x 1) (values))))
                            (declare (notinline f))
                            (multiple-value-bind (a b) (f n)
                              (multiple-value-bind (c d) (f (the fixnum (- n)))
                                (the fixnum (+ (if a a 100) (if b b 200) (if c c 300) (if d d 400)))))))
  (5) (-5) (0))
 ("mv-unknown-three" (n) ((declare (fixnum n))
                          (labels ((f (x) (declare (fixnum x))
                                     (cond ((> x 0) (values x 1 2))
                                           ((< x 0) (values x))
                                           (t (values)))))
                            (declare (notinline f))
                            (multiple-value-bind (a b c) (f n)
                              (multiple-value-bind (d e) (f (the fixnum (- n)))
                                (list a b c d e)))
                            (multiple-value-bind (a b c) (f n)
                              (the fixnum (+ (if a a 10) (if b b 20) (if c c 40))))))
  (5) (-5) (0))
 ("mv-entry-values" (a b) ((declare (fixnum a b)) (values a b)) (1 2) (-3 4))
 ;; Sprint 7: a three-value return with several live values around it
 ;; (the RETURN VOP once let OLD-FP be packed in the NARGS register it
 ;; writes; found in the cold core, see Sprints/Sprint7/develop.md)
 ("mv-entry-values-3" (a b c) ((declare (type (signed-byte 20) a b c))
                               (let ((x (+ a b)) (y (- a c)) (z (* b 2)))
                                 (declare (fixnum x y z))
                                 (values (the fixnum (+ x z)) (the fixnum (- y x)) (the fixnum (+ x y z)))))
  (1 2 3) (-10 20 -30))
 ("mv-entry-no-values" () ((values)) ())
 ("mv-tail-local-unknown" (n) ((declare (fixnum n))
                               (labels ((f (x) (declare (fixnum x))
                                          (if (> x 0) (values x 1) (values))))
                                 (declare (notinline f))
                                 (if (> n 100) (f 1) (f n))))
  (5) (-5) (1000))
 ("mv-prog1" (a) ((declare (fixnum a)) (multiple-value-prog1 (the fixnum (+ a 1)) (the fixnum (+ a 2))))
  (5))

 ;; catch and throw
 ("catch-normal" (a) ((catch 1 a)) (5) (nil))
 ("catch-throw-same-fn" (a) ((declare (fixnum a)) (catch 1 (throw 1 (the fixnum (+ a 1))) 99)) (5) (-1))
 ("catch-throw-t-tag" (a) ((catch t (if a (throw t 10) 20))) (t) (nil))
 ("catch-throw-conditional" (a) ((declare (fixnum a)) (catch 7 (when (> a 0) (throw 7 a)) -1)) (5) (-5))
 ("catch-throw-from-local" (a b) ((declare (fixnum a b))
                                  (labels ((f (x) (declare (fixnum x))
                                             (if (> x 5) (throw 1 x) (the fixnum (* 2 x)))))
                                    (declare (notinline f))
                                    (catch 1 (the fixnum (+ (f a) (f b))))))
  (1 2) (10 2) (1 10))
 ("catch-nested-outer" (a) ((declare (fixnum a)) (catch 1 (catch 2 (throw 1 a)) 99)) (5))
 ("catch-nested-inner" (a) ((declare (fixnum a)) (catch 1 (catch 2 (throw 2 a)) 99)) (5))
 ("catch-throw-mv" (a b) ((declare (fixnum a b))
                          (multiple-value-bind (x y) (catch 1 (throw 1 (values a b)))
                            (the fixnum (- (the fixnum x) (the fixnum y)))))
  (10 3))
 ("catch-normal-mv" (a b) ((declare (fixnum a b))
                           (multiple-value-bind (x y) (catch 1 (values a b))
                             (the fixnum (- (the fixnum x) (the fixnum y)))))
  (10 3))
 ("catch-in-loop" (n) ((declare (type (integer 0 100) n))
                       ;; (an explicit loop: DOTIMES cannot infer the
                       ;; iteration variable's range across the catch, and
                       ;; the generic 1+ would be a full call)
                       (let ((c 0)) (declare (fixnum c))
                         (do ((i 0 (1+ i))) ((>= i n))
                           (declare (type (integer 0 101) i))
                           (catch 1 (when (evenp i) (throw 1 nil)) (setq c (1+ (the (integer 0 1000) c)))))
                         c))
  (0) (1) (10) (11))
 ("catch-throw-deep-local" (n) ((declare (type (integer 0 100) n))
                                (labels ((down (i) (declare (type (integer 0 100) i))
                                           (if (= i 0) (throw 1 -7) (the fixnum (+ 1 (down (1- i)))))))
                                  (catch 1 (down n))))
  (0) (5) (50))

 ;; unwind-protect
 ("uwp-normal" (a) ((declare (fixnum a))
                    (let ((r 0)) (declare (fixnum r))
                      (unwind-protect (setq r a) (setq r (the fixnum (+ r 1))))
                      r))
  (5))
 ("uwp-throw" (a) ((declare (fixnum a))
                   (let ((r 0)) (declare (fixnum r))
                     (catch 1 (unwind-protect (throw 1 a) (setq r (the fixnum (+ r 1)))))
                     r))
  (5))
 ("uwp-throw-value" (a) ((declare (fixnum a))
                         (let ((r 0)) (declare (fixnum r))
                           (the fixnum
                                (+ (the fixnum (catch 1 (unwind-protect (throw 1 a) (setq r 100))))
                                   r))))
  (5))
 ("uwp-nested-throw" (a) ((declare (fixnum a))
                          (let ((r 0)) (declare (fixnum r))
                            (catch 1
                              (unwind-protect
                                   (unwind-protect (throw 1 a) (setq r (the fixnum (+ r 1))))
                                (setq r (the fixnum (+ r 10)))))
                            r))
  (5))
 ("uwp-throw-from-local" (a) ((declare (fixnum a))
                              (let ((r 0)) (declare (fixnum r))
                                (labels ((f (x) (declare (fixnum x)) (throw 1 x)))
                                  (declare (notinline f))
                                  (catch 1 (unwind-protect (f a) (setq r 3)))
                                  (catch 1 (unwind-protect (f a) (setq r (the fixnum (+ r 5))))))
                                r))
  (5))
 ("block-return-from-local" (a) ((declare (fixnum a))
                                 (block b
                                   (labels ((f (x) (declare (fixnum x))
                                              (when (> x 0) (return-from b x)) 0))
                                     (declare (notinline f))
                                     (the fixnum (+ (f a) (f (the fixnum (- a))) 100)))))
  (5) (-5) (0))
 ("uwp-return-from" (a) ((declare (fixnum a))
                         (let ((r 0)) (declare (fixnum r))
                           (block b
                             (unwind-protect (when (> a 0) (return-from b nil))
                               (setq r (the fixnum (+ r 1)))))
                           r))
  (5) (-5))

 ;; dynamic extent
 ("dx-list" (a b) ((declare (fixnum a b))
                   (let ((l (list a b))) (declare (dynamic-extent l))
                     (the fixnum (+ (the fixnum (car l)) (the fixnum (cadr l))))))
  (1 2) (-5 5))
 ("dx-cons" (a) ((let ((c (cons a a))) (declare (dynamic-extent c)) (car c))) (5) (nil))

 ;; entry points with optional and rest arguments
 ("optional-arg" (a &optional (b 10)) ((declare (fixnum a b)) (the fixnum (+ a b))) (1) (1 2))
 ("optional-two" (a &optional (b 10) (c 100)) ((declare (fixnum a b c)) (the fixnum (+ a b c)))
  (1) (1 2) (1 2 3))
 ("optional-supplied" (a &optional (b 0 b-p)) ((declare (fixnum a b)) (if b-p (the fixnum (- a b)) a))
  (7) (7 2))
 ("rest-count" (a &rest r) ((declare (fixnum a) (ignore a))
                            (let ((c 0)) (declare (fixnum c))
                              (dolist (x r) (declare (ignore x)) (incf c))
                              c))
  (1) (1 2) (1 2 3) (1 2 3 4) (1 2 3 4 5) (1 2 3 4 5 6))
 ("rest-sum" (&rest r) ((let ((s 0)) (declare (fixnum s))
                          (dolist (x r) (setq s (the fixnum (+ s (the fixnum x)))))
                          s))
  () (1) (1 2) (1 2 3 4 5 6 7))
 ("rest-first" (a &rest r) ((if r (car r) a)) (1) (1 2) (1 2 3))
 ("rest-after-two" (a b &rest r) ((declare (fixnum a b))
                                  (if r
                                      (let ((l r)) (loop while (cdr l) do (setq l (cdr l))) (car l))
                                      (the fixnum (+ a b))))
  (1 2) (1 2 3) (1 2 3 4 5))
 ("more-arg-values" (&rest r) ((declare (dynamic-extent r))
                               (let ((s 0)) (declare (fixnum s))
                                 (dolist (x r) (setq s (the fixnum (+ s (the fixnum x)))))
                                 s))
  () (1 2 3) (1 2 3 4 5 6))

 ;; floats (values made from fixnums; results truncated to fixnums)
 ("sf-add" (a b) ((declare (type (integer -1000 1000) a b))
                  (truncate (+ (coerce a 'single-float) (coerce b 'single-float))))
  (1 2) (-5 3))
 ("sf-mul" (a b) ((declare (type (integer -1000 1000) a b))
                  (truncate (* (coerce a 'single-float) (coerce b 'single-float))))
  (6 7) (-5 3) (0 9))
 ("sf-div" (a b) ((declare (type (integer -1000 1000) a) (type (integer 1 1000) b))
                  (truncate (/ (coerce a 'single-float) (coerce b 'single-float))))
  (7 2) (-7 2) (100 3))
 ;; (float literals would be boxed constants, so the zero is an argument)
 ("sf-sub-lt" (a b z) ((declare (type (integer -1000 1000) a b z))
                       (< (- (coerce a 'single-float) (coerce b 'single-float)) (coerce z 'single-float)))
  (1 2 0) (2 1 0) (3 3 0) (3 3 1))
 ("sf-compare" (a b) ((declare (type (integer -1000 1000) a b))
                      (let ((x (coerce a 'single-float)) (y (coerce b 'single-float)))
                        (cond ((< x y) -1) ((> x y) 1) (t 0))))
  (1 2) (2 1) (3 3))
 ("sf-eq" (a b) ((declare (type (integer -1000 1000) a b))
                 (= (coerce a 'single-float) (coerce b 'single-float)))
  (1 2) (3 3))
 ("sf-abs-neg" (a) ((declare (type (integer -1000 1000) a))
                    (truncate (- (abs (coerce a 'single-float)))))
  (5) (-5) (0))
 ("sf-round" (a b) ((declare (type (integer -1000 1000) a) (type (integer 1 1000) b))
                    (round (/ (coerce a 'single-float) (coerce b 'single-float))))
  (7 2) (5 2) (-7 2) (1 3))
 ("sf-loop-sum" (n hi lo z) ((declare (type (integer 0 100) n) (type (integer 0 1000000) hi) (type (integer -1000000 0) lo) (type (integer 0 1) z))
                     ;; the sum is clamped between argument-derived bounds
                     ;; so that TRUNCATE has a fixnum result (a bounded
                     ;; float declaration would compare against boxed
                     ;; constants, which the rig cannot provide)
                     (let ((s (coerce z 'single-float)))
                       (declare (type single-float s))
                       (dotimes (i n) (setq s (+ s (coerce i 'single-float))))
                       (truncate (max (min s (coerce hi 'single-float)) (coerce lo 'single-float)))))
  (0 100000 -100000 0) (1 100000 -100000 0) (10 100000 -100000 1) (100 100000 -100000 0) (100 10 -100000 0))
 ("df-add" (a b) ((declare (type (integer -1000 1000) a b))
                  (truncate (+ (coerce a 'double-float) (coerce b 'double-float))))
  (1 2) (-5 3))
 ("df-mul" (a b) ((declare (type (integer -1000 1000) a b))
                  (truncate (* (coerce a 'double-float) (coerce b 'double-float))))
  (6 7) (-5 3) (0 9))
 ("df-div" (a b) ((declare (type (integer -1000 1000) a) (type (integer 1 1000) b))
                  (truncate (/ (coerce a 'double-float) (coerce b 'double-float))))
  (7 2) (-7 2) (100 3))
 ("df-compare" (a b) ((declare (type (integer -1000 1000) a b))
                      (let ((x (coerce a 'double-float)) (y (coerce b 'double-float)))
                        (cond ((< x y) -1) ((> x y) 1) (t 0))))
  (1 2) (2 1) (3 3))
 ("df-eq" (a b) ((declare (type (integer -1000 1000) a b))
                 (= (coerce a 'double-float) (coerce b 'double-float)))
  (1 2) (3 3))
 ("df-round" (a b) ((declare (type (integer -1000 1000) a) (type (integer 1 1000) b))
                    (round (/ (coerce a 'double-float) (coerce b 'double-float))))
  (7 2) (5 2) (-7 2) (1 3))
 ("df-loop-sum" (n hi lo) ((declare (type (integer 0 100) n) (type (integer 0 1000000) hi) (type (integer -1000000 0) lo))
                     (let ((s (coerce 0 'double-float)))
                       (declare (type double-float s))
                       (dotimes (i n) (setq s (+ s (coerce i 'double-float))))
                       (truncate (max (min s (coerce hi 'double-float)) (coerce lo 'double-float)))))
  (0 100000 -100000) (1 100000 -100000) (10 100000 -100000) (100 100000 -100000) (100 10 -100000))
 ("sf-to-df" (a b) ((declare (type (integer -1000 1000) a b))
                    (truncate (+ (coerce (coerce a 'single-float) 'double-float)
                                 (coerce b 'double-float))))
  (1 2) (-5 3))
 ("df-to-sf" (a b) ((declare (type (integer -1000 1000) a b))
                    (truncate (+ (coerce (coerce a 'double-float) 'single-float)
                                 (coerce b 'single-float))))
  (1 2) (-5 3))
 ("sf-local-call" (a b two) ((declare (type (integer -1000 1000) a b) (type (integer 1 10) two))
                             (labels ((avg (x y) (declare (type (single-float -1e6 1e6) x y))
                                        (/ (+ x y) (coerce two 'single-float))))
                               (declare (notinline avg))
                               (truncate (+ (avg (coerce a 'single-float) (coerce b 'single-float))
                                            (avg (coerce b 'single-float) (coerce a 'single-float))))))
  (1 3 2) (-10 4 2) (7 9 4))
 ("df-local-call-mv" (a b three hi lo) ((declare (type (integer -1000 1000) a) (type (integer 1 1000) b three)
                                        (type (integer 1000 100000) hi) (type (integer -100000 -1000) lo))
                                        ;; quotients and remainders are clamped between HI and LO
                                        ;; (arguments: literals would be boxed constants) so that
                                        ;; TRUNCATE has a word result, cast to a fixnum before adding
                                        (let ((hi (coerce hi 'double-float)) (lo (coerce lo 'double-float)))
                                          (labels ((qr (x y) (declare (type double-float x y))
                                                     (let ((q (truncate (max (min (/ x y) hi) lo))))
                                                       (values q (- x (* (coerce q 'double-float) y))))))
                                            (declare (notinline qr))
                                            (multiple-value-bind (q r) (qr (coerce a 'double-float) (coerce b 'double-float))
                                              (multiple-value-bind (q2 r2) (qr (coerce b 'double-float) (coerce three 'double-float))
                                                (the fixnum
                                                     (+ (the fixnum (+ (the fixnum q)
                                                                       (the fixnum (truncate (max (min r hi) lo)))))
                                                        (the fixnum (+ (the fixnum q2)
                                                                       (the fixnum (truncate (max (min r2 hi) lo))))))))))))
  (17 5 3 1000 -1000) (-17 5 3 1000 -1000) (100 7 4 1000 -1000))
 ("sf-bits" (a) ((declare (type (integer -1000 1000) a))
                 (logand (ash (single-float-bits (coerce a 'single-float)) -23) #xFF))
  (1) (2) (-1) (0))
 ("df-high-bits" (a) ((declare (type (integer -1000 1000) a))
                      (logand (ash (double-float-high-bits (coerce a 'double-float)) -20) #x7FF))
  (1) (2) (-1) (0))
 ("mv-double-values" (a b) ((declare (type (integer -1000 1000) a b))
                            (labels ((f (x y) (declare (type double-float x y)) (values y x)))
                              (declare (notinline f))
                              (multiple-value-bind (p q) (f (coerce a 'double-float) (coerce b 'double-float))
                                (multiple-value-bind (p2 q2) (f p q)
                                  (+ (if (< p q) 1 0) (if (< p2 q2) 2 0) (if (= p q2) 4 0) (if (= q p2) 8 0)
                                     (if (= p (coerce b 'double-float)) 16 0) (if (= q (coerce a 'double-float)) 32 0))))))
  (1 2) (2 1) (5 5))
)
