;;;; Differential test cases for the WebAssembly backend, level 1.
;;;; (name lambda-list body args-list...) — each args-list is one case.
;;;;
;;;; Arguments and results are raw register words, so only fixnums,
;;;; characters, T and NIL cross the boundary. The functions must not need
;;;; full calls (the call convention is a later sprint): everything they do
;;;; is open-coded, with type declarations narrow enough that the compiler
;;;; picks the inline VOPs. Error paths (type checks, division by zero) are
;;;; traps into the runtime, which is fine.
(
 ;; constants and arguments
 ("const-42" () ((declare (optimize (safety 0))) 42) ())
 ("identity-fixnum" (a) ((declare (fixnum a)) a) (7) (-7) (0))
 ("first-of-two" (a b) ((declare (fixnum a b)) (progn b a)) (1 2))
 ("second-of-two" (a b) ((declare (fixnum a b)) (progn a b)) (1 2))
 ("const-char" () (#\A) ())
 ("const-nil" () (nil) ())
 ("const-t" () (t) ())
 ("const-big-fixnum" () (123456789) ())
 ("const-negative" () (-100000) ())

 ;; fixnum arithmetic
 ("add" (a b) ((declare (fixnum a b)) (the fixnum (+ a b))) (1 2) (-5 3) (100000 200000))
 ("sub" (a b) ((declare (fixnum a b)) (the fixnum (- a b))) (1 2) (-5 3) (300000 200000))
 ("add-c" (a) ((declare (fixnum a)) (the fixnum (+ a 10))) (1) (-20))
 ("sub-c" (a) ((declare (fixnum a)) (the fixnum (- a 10))) (1) (-20))
 ("one-plus" (a) ((declare (fixnum a)) (the fixnum (1+ a))) (41) (-1))
 ("one-minus" (a) ((declare (fixnum a)) (the fixnum (1- a))) (43) (0))
 ("negate" (a) ((declare (fixnum a)) (the fixnum (- a))) (5) (-5) (0))
 ("mul" (a b) ((declare (type (signed-byte 14) a b)) (* a b)) (6 7) (-3 4) (0 9) (-100 -100))
 ("mul-c" (a) ((declare (type (signed-byte 20) a)) (* a 12)) (6) (-3))
 ("truncate-q" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (values (truncate a b)))
  (17 5) (-17 5) (100 10))
 ("truncate-r" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (nth-value 1 (truncate a b)))
  (17 5) (-17 5) (100 10))
 ("rem" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (rem a b)) (17 5) (-17 5))
 ("mod" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (mod a b)) (17 5) (-17 5))
 ("floor-q" (a b) ((declare (fixnum a) (type (integer 1 1000) b)) (values (floor a b))) (17 5) (-17 5))
 ("abs" (a) ((declare (type (signed-byte 20) a)) (abs a)) (5) (-5) (0))
 ("max" (a b) ((declare (fixnum a b)) (max a b)) (1 2) (2 1) (-3 -4))
 ("min" (a b) ((declare (fixnum a b)) (min a b)) (1 2) (2 1) (-3 -4))
 ("mv-bind-truncate" (a b) ((declare (fixnum a) (type (integer 1 1000) b))
                            (multiple-value-bind (q r) (truncate a b) (the fixnum (+ q r))))
  (17 5) (-17 5))

 ;; logical operations and shifts
 ("logand" (a b) ((declare (fixnum a b)) (logand a b)) (12 10) (-1 255) (0 7))
 ("logior" (a b) ((declare (fixnum a b)) (logior a b)) (12 10) (-8 3) (0 7))
 ("logxor" (a b) ((declare (fixnum a b)) (logxor a b)) (12 10) (-1 255) (5 5))
 ("lognot" (a) ((declare (fixnum a)) (lognot a)) (0) (5) (-6))
 ("logand-c" (a) ((declare (fixnum a)) (logand a 255)) (300) (-1) (0))
 ("logior-c" (a) ((declare (fixnum a)) (logior a 256)) (1) (256) (-1))
 ("logxor-c" (a) ((declare (fixnum a)) (logxor a 3)) (1) (0) (-1))
 ("logtest" (a b) ((declare (fixnum a b)) (logtest a b)) (12 4) (12 3))
 ("ash-left-c" (a) ((declare (type (signed-byte 16) a)) (ash a 3)) (5) (-5) (0))
 ("ash-right-c" (a) ((declare (fixnum a)) (ash a -3)) (40) (-40) (7))
 ("ash-left-var" (a b) ((declare (type (unsigned-byte 8) a) (type (integer 0 8) b)) (ash a b))
  (5 3) (255 8) (1 0))
 ("ash-right-var" (a b) ((declare (fixnum a) (type (integer -31 0) b)) (ash a b))
  (40 -3) (-40 -3) (7 0) (100 -31))
 ("ash-var-signed" (a b) ((declare (type (signed-byte 16) a) (type (integer -40 8) b)) (ash a b))
  (5 3) (-5 3) (40 -3) (-40 -3) (-40 -40) (12 -40))
 ("ldb" (a) ((declare (fixnum a)) (ldb (byte 8 4) a)) (4095) (-1) (16))
 ("integer-length" (a) ((declare (fixnum a)) (integer-length a)) (0) (1) (255) (256) (-1) (-256))
 ("logcount" (a) ((declare (type (unsigned-byte 29) a)) (logcount a)) (0) (255) (1023) (#x0AAAAAAA))
 ("evenp" (a) ((declare (fixnum a)) (evenp a)) (4) (5) (-2))
 ("oddp" (a) ((declare (fixnum a)) (oddp a)) (4) (5) (-3))

 ;; comparisons
 ("less" (a b) ((declare (fixnum a b)) (< a b)) (1 2) (2 1) (3 3) (-5 2))
 ("greater" (a b) ((declare (fixnum a b)) (> a b)) (1 2) (2 1) (3 3) (-5 2))
 ("less-equal" (a b) ((declare (fixnum a b)) (<= a b)) (1 2) (2 1) (3 3))
 ("greater-equal" (a b) ((declare (fixnum a b)) (>= a b)) (1 2) (2 1) (3 3))
 ("num-equal" (a b) ((declare (fixnum a b)) (= a b)) (1 2) (3 3) (-3 -3))
 ("num-not-equal" (a b) ((declare (fixnum a b)) (/= a b)) (1 2) (3 3))
 ("eql-fixnum" (a b) ((declare (fixnum a b)) (eql a b)) (1 2) (3 3))
 ("eq" (a b) ((eq a b)) (1 2) (3 3) (t t) (nil t))
 ("zerop" (a) ((declare (fixnum a)) (zerop a)) (0) (1) (-1))
 ("plusp" (a) ((declare (fixnum a)) (plusp a)) (0) (1) (-1))
 ("minusp" (a) ((declare (fixnum a)) (minusp a)) (0) (1) (-1))
 ("less-c" (a) ((declare (fixnum a)) (< a 100)) (99) (100) (101))
 ("in-range" (a) ((declare (fixnum a)) (typep a '(integer 0 10))) (-1) (0) (5) (10) (11))

 ;; control flow
 ("if-then-else" (a) ((if a 1 2)) (t) (nil) (5))
 ("not" (a) ((not a)) (t) (nil) (5))
 ("null" (a) ((null a)) (t) (nil) (5))
 ("and" (a b) ((and a b)) (t 5) (nil 5) (5 nil))
 ("or" (a b) ((or a b)) (t 5) (nil 5) (nil nil))
 ("cond-sign" (a) ((declare (fixnum a)) (cond ((< a 0) -1) ((> a 0) 1) (t 0))) (-7) (7) (0))
 ("when-unless" (a) ((declare (fixnum a)) (let ((r 0)) (declare (fixnum r))
                                              (when (> a 5) (setq r 1))
                                              (unless (> a 5) (setq r 2))
                                              r))
  (3) (9))
 ("sum-loop" (n) ((declare (type (integer 0 10000) n))
                  (let ((s 0)) (declare (type (integer 0 100000000) s))
                    (dotimes (i n) (setq s (+ s i)))
                    s))
  (0) (1) (10) (100))
 ("count-down" (n) ((declare (type (integer 0 10000) n))
                    (let ((c 0)) (declare (fixnum c))
                      (loop while (> n 0) do (setq n (1- n)) (setq c (the fixnum (+ c 2))))
                      c))
  (0) (5))
 ("fib-iter" (n) ((declare (type (integer 0 30) n))
                  (let ((a 0) (b 1)) (declare (type (integer 0 10000000) a b))
                    (dotimes (i n) (let ((c (+ a b))) (setq a b b c)))
                    a))
  (0) (1) (2) (10) (20))
 ("let-shadow" (a) ((declare (fixnum a)) (let ((a (the fixnum (+ a 1)))) (let ((a (the fixnum (* 2 a)))) a)))
  (5) (-1))
 ("flet-inline" (a b) ((declare (fixnum a b)) (flet ((sq+ (x y) (declare (fixnum x y)) (the fixnum (+ x y)))) (sq+ a b)))
  (3 4))

 ;; characters
 ("char-code" (c) ((char-code c)) (#\a) (#\Z) (#\Space))
 ("code-char" (n) ((declare (type (integer 0 255) n)) (code-char n)) (65) (97) (32))
 ("char=" (a b) ((char= a b)) (#\a #\a) (#\a #\b))
 ("char<" (a b) ((char< a b)) (#\a #\b) (#\b #\a) (#\a #\a))
 ("char>" (a b) ((char> a b)) (#\a #\b) (#\b #\a))
 ("char-roundtrip" (c) ((code-char (1+ (char-code c)))) (#\a) (#\A))
 ("characterp" (a) ((characterp a)) (#\a) (5) (nil) (t))

 ;; lists (allocation through the runtime)
 ("cons-car" (a b) ((car (cons a b))) (1 2) (t nil) (#\a 3))
 ("cons-cdr" (a b) ((cdr (cons a b))) (1 2) (t nil) (#\a 3))
 ("consp" (a) ((consp a)) (1) (nil) (t) (#\a))
 ("consp-cons" (a) ((consp (cons a a))) (1))
 ("listp" (a) ((listp a)) (1) (nil) (t))
 ("list-cadr" (a b c) ((cadr (list a b c))) (1 2 3) (nil t nil))
 ("list-sum" (a b c) ((declare (fixnum a b c))
                      (let ((l (list a b c)))
                        (the fixnum (+ (the fixnum (car l)) (the fixnum (cadr l)) (the fixnum (caddr l))))))
  (1 2 3) (10 -20 30))
 ("list-star" (a b) ((cdr (list* a b))) (1 2) (nil t))
 ("rplaca" (a b c) ((let ((x (cons a b))) (setf (car x) c) (car x))) (1 2 3))
 ("rplacd" (a b c) ((let ((x (cons a b))) (setf (cdr x) c) (cdr x))) (1 2 3))
 ("endp" (a) ((endp (list a))) (1))
 ("list-length-loop" (n) ((declare (type (integer 0 100) n))
                          (let ((l nil)) (dotimes (i n) (setq l (cons i l)))
                            (let ((c 0)) (declare (fixnum c))
                              (loop while l do (setq l (cdr l)) (incf c))
                              c)))
  (0) (3) (50))

 ;; symbols and type predicates
 ("symbolp" (a) ((symbolp a)) (t) (nil) (1) (#\a))
 ("integerp" (a) ((integerp a)) (1) (-1) (nil) (#\a) (t))
 ("numberp" (a) ((numberp a)) (1) (nil) (#\a))
 ("fixnump" (a) ((typep a 'fixnum)) (1) (nil) (#\a))
 ("stringp" (a) ((stringp a)) (1) (nil) (t))
 ("functionp" (a) ((functionp a)) (1) (nil) (t))
 ("vectorp" (a) ((vectorp a)) (1) (nil) (#\a))
 ("eq-t" (a) ((eq a t)) (t) (nil) (1))
 ("case-fixnum" (a) ((declare (fixnum a)) (case a (1 10) (2 20) ((3 4) 30) (t 0))) (1) (2) (3) (4) (5))
)
