(in-package :cl-test)
(defun diag-nsp () (let ((v (sb-sys:%primitive sb-c:current-nsp))) (if (sb-sys:system-area-pointer-p v) (sb-sys:sap-int v) v)))
(defun diag-csp () (sb-alien:alien-funcall (sb-alien:extern-alien "c_stack_save" (function sb-alien:unsigned))))
(defun diag-raw-ph (keys)
  (let* ((keys (coerce keys '(simple-array (unsigned-byte 32) (*))))
         (ptr (sb-sys:with-pinned-objects (keys)
                (sb-alien:alien-funcall
                 (sb-alien:extern-alien "lisp_perfhash_with_options"
                                        (function sb-sys:system-area-pointer sb-alien:int sb-sys:system-area-pointer sb-alien:int))
                 1 (sb-sys:vector-sap keys) (length keys)))))
    (if (zerop (sb-sys:sap-int ptr))
        :null
        (let ((bytes (loop for i from 0 below 400
                           for b = (sb-sys:sap-ref-8 ptr i)
                           until (zerop b) collect b)))
          (list :length (length bytes)
                :high (count-if (lambda (b) (>= b 128)) bytes)
                :text (map 'string (lambda (b) (if (< b 128) (code-char b) #\?)) bytes))))))
(defun diag (label)
  (format t "~&;; DIAG ~A: nsp=~X csp=~X consed=~D~%" label (diag-nsp) (diag-csp) (sb-ext:get-bytes-consed))
  (let ((keys (vector #xD0C591 #xC841474 #x11D1FAD #x12F86037 #x35ED22C)))
    (format t ";;   raw: ~S~%" (diag-raw-ph keys))
    (format t ";;   lambda: ~A~%"
            (handler-case (progn (sb-c::compile-perfect-hash (sb-c:make-perfect-hash-lambda keys) keys) :ok)
              (error (c) (subseq (princ-to-string c) 0 (min 150 (length (princ-to-string c))))))))
  (finish-output))
(diag "start")
(let ((names (rt:pending-tests)) (n 0) (*standard-output* (make-broadcast-stream)) (*error-output* (make-broadcast-stream)))
  (dolist (name names)
    (rt:do-test name)
    (incf n)
    (when (member n '(1000 3000 5000 6000 6500 6700))
      (let ((*standard-output* sb-sys:*stdout*)) (diag n)))
    (when (>= n 6725) (return))))
(diag "end")
(rt:do-test 'set-difference.16)
(rt:do-test 'format.e.3)
(sb-ext:exit)
