#!/bin/sh
# Generate src/runtime/wasm-linkage-table.c from the list of foreign
# symbols genesis writes next to the core module (<core>-core.wasm.symbols,
# lines "index kind name"): the runtime's answer to os_dlsym_default,
# since there is no dynamic symbol lookup on WebAssembly
# (doc/wasm-port/02-design.md, 2.9).
# Usage: wasm-linkage-table.sh SYMBOLS > wasm-linkage-table.c
set -e
symbols=$1
cat <<HEADER
/* Generated by tools-for-build/wasm-linkage-table.sh from $symbols. Do not edit. */
/* No headers: the declarations below are address-only and must not
 * conflict with the real prototypes. */
struct wasm_linkage_entry { const char *name; void *address; };
#pragma clang diagnostic ignored "-Wincompatible-library-redeclaration"
HEADER
# A call through the table must have exactly the C function's Wasm type;
# where the Lisp declaration (fixed by SYSCALL) differs from the C
# prototype, the entry names a wrapper with the declared type
# (src/runtime/wasm-arch.c). Lisp name -> C symbol:
alias() {
    case "$1" in
        exit) echo wasm_exit_int ;;
        _exit) echo wasm__exit_int ;;
        *) echo "$1" ;;
    esac
}
# declarations
while read -r index kind name; do
    c=$(alias "$name")
    case "$kind" in
        function) echo "extern void $c(void);" ;;
        data) echo "extern char $c[];" ;;
    esac
done < "$symbols"
echo "const struct wasm_linkage_entry wasm_linkage_table[] = {"
while read -r index kind name; do
    echo "    { \"$name\", (void*)$(alias "$name") },"
done < "$symbols"
cat <<FOOTER
    { 0, 0 }
};
static int same_name(const char *a, const char *b)
{
    while (*a && *a == *b) { a++; b++; }
    return *a == *b;
}
void *wasm_linkage_lookup(const char *name)
{
    const struct wasm_linkage_entry *e;
    for (e = wasm_linkage_table; e->name; e++)
        if (same_name(e->name, name)) return e->address;
    return 0;
}
FOOTER
