#!/bin/sh
# Generate src/runtime/wasm-linkage-table.c from the list of foreign
# symbols genesis writes next to the core module (<core>-core.wasm.symbols,
# lines "index kind name"): the runtime's answer to os_dlsym_default,
# since there is no dynamic symbol lookup on WebAssembly
# (doc/wasm-port/02-design.md, 2.9).
# Usage: wasm-linkage-table.sh SYMBOLS > wasm-linkage-table.c
set -e
symbols=$1
cat <<HEADER
/* Generated by tools-for-build/wasm-linkage-table.sh from $symbols. Do not edit. */
/* No headers: the declarations below are address-only and must not
 * conflict with the real prototypes. */
struct wasm_linkage_entry { const char *name; void *address; };
#pragma clang diagnostic ignored "-Wincompatible-library-redeclaration"
HEADER
# declarations
awk '$2 == "function" { printf "extern void %s(void);\n", $3 }
     $2 == "data"     { printf "extern char %s[];\n", $3 }' "$symbols"
echo "const struct wasm_linkage_entry wasm_linkage_table[] = {"
awk '{ printf "    { \"%s\", (void*)%s },\n", $3, $3 }' "$symbols"
cat <<FOOTER
    { 0, 0 }
};
static int same_name(const char *a, const char *b)
{
    while (*a && *a == *b) { a++; b++; }
    return *a == *b;
}
void *wasm_linkage_lookup(const char *name)
{
    const struct wasm_linkage_entry *e;
    for (e = wasm_linkage_table; e->name; e++)
        if (same_name(e->name, name)) return e->address;
    return 0;
}
FOOTER
