;;;; Print DEFINE-VOP skeletons for the VOPs named in NEEDED-FILE, taking
;;;; the operand, info and type clauses from the VOP-PARSE objects of the
;;;; cross-compiler image this runs in (a riscv32 xc.core), and replacing
;;;; every generator with VOP-NOT-YET-IMPLEMENTED. Output goes to
;;;; OUT-DIR/<file>.lisp, one file per source file of the original.
;;;;
;;;; usage: sbcl --core obj/xbuild/riscv32/xc.core --load this --eval '(gen "/tmp/needed.txt" "/tmp/skel/")'

(in-package "SB-VM")

(defun operand-form (op)
  (let ((form (list (sb-c::operand-parse-name op))))
    (let ((scs (sb-c::operand-parse-scs op)))
      (when scs (setf form (append form (list :scs (if (listp scs) scs (list scs)))))))
    (when (sb-c::operand-parse-target op)
      (setf form (append form (list :target (sb-c::operand-parse-target op)))))
    (unless (eq (sb-c::operand-parse-load op) t)
      (setf form (append form (list :load-if (sb-c::operand-parse-load op)))))
    (when (eq (sb-c::operand-parse-kind op) :more-argument)
      (setf form (append form (list :more t))))
    (when (eq (sb-c::operand-parse-kind op) :more-result)
      (setf form (append form (list :more t))))
    form))

(defun skeleton (parse)
  (let ((name (sb-c::vop-parse-name parse))
        (clauses '()))
    (flet ((add (clause) (push clause clauses)))
      (let ((args (append (mapcar #'operand-form (sb-c::vop-parse-args parse))
                          (when (sb-c::vop-parse-more-args parse)
                            (list (operand-form (sb-c::vop-parse-more-args parse)))))))
        (add `(:args ,@args)))
      (let ((results (append (mapcar #'operand-form (sb-c::vop-parse-results parse))
                             (when (sb-c::vop-parse-more-results parse)
                               (list (operand-form (sb-c::vop-parse-more-results parse)))))))
        (when results (add `(:results ,@results))))
      (unless (eq (sb-c::vop-parse-arg-types parse) :unspecified)
        (add `(:arg-types ,@(sb-c::vop-parse-arg-types parse))))
      (unless (eq (sb-c::vop-parse-result-types parse) :unspecified)
        (add `(:result-types ,@(sb-c::vop-parse-result-types parse))))
      (when (sb-c::vop-parse-info-args parse)
        (add `(:info ,@(sb-c::vop-parse-info-args parse))))
      (let ((c (sb-c::vop-parse-conditional-p parse)))
        (when c (add (if (listp c) `(:conditional ,@c) '(:conditional)))))
      (when (sb-c::vop-parse-translate parse)
        (add `(:translate ,@(sb-c::vop-parse-translate parse))))
      (unless (eq (sb-c::vop-parse-ltn-policy parse) :fast)
        (add `(:policy ,(sb-c::vop-parse-ltn-policy parse))))
      (when (sb-c::vop-parse-save-p parse)
        (add `(:save-p ,(sb-c::vop-parse-save-p parse))))
      (when (sb-c::vop-parse-move-args parse)
        (add `(:move-args ,(sb-c::vop-parse-move-args parse))))
      (when (sb-c::vop-parse-variant-vars parse)
        (add `(:variant-vars ,@(sb-c::vop-parse-variant-vars parse))))
      (when (sb-c::vop-parse-variant parse)
        (add `(:variant ,@(sb-c::vop-parse-variant parse))))
      (when (sb-c::vop-parse-optional-results parse)
        (add `(:optional-results ,@(sb-c::vop-parse-optional-results parse))))
      (when (sb-c::vop-parse-note parse)
        (add `(:note ,(sb-c::vop-parse-note parse))))
      (when (sb-c::vop-parse-guard parse)
        (add `(:guard ,(sb-c::vop-parse-guard parse))))
      (unless (eq (sb-c::vop-parse-vop-var parse) 'sb-c::.vop.)
        (add `(:vop-var ,(sb-c::vop-parse-vop-var parse))))
      (when (sb-c::vop-parse-node-var parse)
        (add `(:node-var ,(sb-c::vop-parse-node-var parse))))
      ;; every operand is unused by the placeholder generator
      (let ((names (append (mapcar #'sb-c::operand-parse-name (sb-c::vop-parse-args parse))
                           (mapcar #'sb-c::operand-parse-name (sb-c::vop-parse-results parse))
                           (when (sb-c::vop-parse-more-args parse)
                             (list (sb-c::operand-parse-name (sb-c::vop-parse-more-args parse))))
                           (when (sb-c::vop-parse-more-results parse)
                             (list (sb-c::operand-parse-name (sb-c::vop-parse-more-results parse))))
                           (sb-c::vop-parse-info-args parse))))
        (when names (add `(:ignore ,@names))))
      (add `(:generator ,(sb-c::vop-parse-cost parse)
              (vop-not-yet-implemented ',name))))
    `(define-vop (,name) ,@(nreverse clauses))))

(defun gen (needed-file out-dir)
  ;; NEEDED-FILE has one "vop-name file-stem" pair per line.
  (let ((needed (with-open-file (s needed-file)
                  (loop for line = (read-line s nil) while line
                        for space = (position #\Space line)
                        for token = (string-upcase (subseq line 0 space))
                        for colon = (position #\: token)
                        for sym = (if colon
                                      (find-symbol (string-left-trim ":" (subseq token colon))
                                                   (subseq token 0 colon))
                                      (find-symbol token "SB-VM"))
                        when sym collect (cons sym (subseq line (1+ space))))))
        (by-file (make-hash-table :test 'equal)))
    (loop for (name . stem) in needed
          do (let ((parse (gethash name sb-c::*backend-parsed-vops*)))
               (when parse
                 (push (skeleton parse) (gethash stem by-file)))))
    (ensure-directories-exist out-dir)
    (maphash (lambda (stem forms)
               (with-open-file (out (format nil "~A~A.lisp" out-dir stem)
                                    :direction :output :if-exists :supersede)
                 (let ((*package* (find-package "SB-VM"))
                       (*print-case* :downcase)
                       (*print-right-margin* 90)
                       (*print-pretty* t))
                   (dolist (form (nreverse forms))
                     (pprint form out)
                     (terpri out)))
                 (format t "~&~A: ~D VOPs~%" stem (length forms))))
             by-file)))
