#!/usr/bin/env python3
"""Append generated VOP skeletons (from /tmp/skel/<stem>.lisp) to the wasm
backend files, skipping VOPs the wasm files already define."""
import os, re, sys
skel = sys.argv[1] if len(sys.argv) > 1 else "/tmp/skel/"
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
wasm = os.path.join(root, "src/compiler/wasm")
defined = set()
for f in os.listdir(wasm):
    if f.endswith(".lisp"):
        defined |= set(re.findall(r"\(define-vop \(([^ )]+)", open(os.path.join(wasm, f)).read()))
for f in sorted(os.listdir(skel)):
    if not f.endswith(".lisp"): continue
    forms, cur, depth = [], "", 0
    text = open(os.path.join(skel, f)).read()
    # split top-level forms by paren depth (no strings with parens in skeletons)
    for ch in text:
        if ch == "(":
            if depth == 0: cur = ""
            depth += 1
        if depth > 0: cur += ch
        if ch == ")":
            depth -= 1
            if depth == 0: forms.append(cur)
    forms = [re.sub(r" :target [^ )]+", "", x) for x in forms]
    kept = [x for x in forms if re.match(r"\(define-vop \(([^ )]+)", x).group(1) not in defined]
    target = os.path.join(wasm, f)
    with open(target, "a") as out:
        out.write("\n;;;; Skeletons: operand shapes taken from the riscv backend, generators to\n"
                  ";;;; be written in Sprint 3. Generated by Sprints/Sprint2/gen-skeletons.lisp.\n")
        for x in kept:
            out.write("\n" + x + "\n")
    print(f"{f}: appended {len(kept)} of {len(forms)}")
