;;; Sprint 11: snapshot of the low memory after every ANSI test (develop.md, section 1)
(in-package :cl-test)
;; the null page and the runtime's statics up to the register area
(defparameter *ranges* '((#x0 . #xc150)))
(defun snapshot-size () (loop for (a . b) in *ranges* sum (floor (- b a) 4)))
(defun take-snapshot (into)
  (let ((i 0))
    (dolist (r *ranges*)
      (loop for a from (car r) below (cdr r) by 4
            do (setf (aref into i) (sb-sys:sap-ref-32 (sb-sys:int-sap a) 0)) (incf i)))
    into))
(defun word-address (i)
  (dolist (r *ranges*)
    (let ((n (floor (- (cdr r) (car r)) 4)))
      (if (< i n) (return (+ (car r) (* 4 i))) (decf i n)))))
(defvar *n* (snapshot-size))
(defvar *prev* (take-snapshot (make-array *n* :element-type '(unsigned-byte 32))))
(defvar *cur* (make-array *n* :element-type '(unsigned-byte 32)))
(format t "~&;; ~D words watched~%" *n*)
(let ((n 0) (out *standard-output*) (reports 0))
  (dolist (name (rt:pending-tests))
    (let ((*standard-output* (make-broadcast-stream)) (*error-output* (make-broadcast-stream)))
      (rt:do-test name))
    (incf n)
    (take-snapshot *cur*)
    (let ((changed 0))
      (dotimes (i *n*)
        (unless (= (aref *cur* i) (aref *prev* i))
          (when (< changed 12)
            (format out "~&;; test ~D ~A: ~8,'0X  ~8,'0X -> ~8,'0X~%" n name (word-address i) (aref *prev* i) (aref *cur* i)))
          (incf changed)))
      (when (> changed 0)
        (format out ";; test ~D ~A: ~D words changed~%" n name changed)
        (finish-output out)
        (when (>= (incf reports) 25) (return))))
    (rotatef *prev* *cur*)
    (when (>= n 4600) (format out "~&;; through ~D tests~%" n) (return))))
(sb-ext:exit)
