;;; Sprint 11: the generator check with SBCL_WASM_WATCH and per-test progress (develop.md, section 1)
(in-package :cl-test)
(defun diag-raw-ph (keys)
  (let* ((keys (coerce keys '(simple-array (unsigned-byte 32) (*))))
         (ptr (sb-sys:with-pinned-objects (keys)
                (sb-alien:alien-funcall
                 (sb-alien:extern-alien "lisp_perfhash_with_options"
                                        (function sb-sys:system-area-pointer sb-alien:int sb-sys:system-area-pointer sb-alien:int))
                 1 (sb-sys:vector-sap keys) (length keys)))))
    (if (zerop (sb-sys:sap-int ptr))
        :null
        (prog1 (map 'string (lambda (b) (if (< b 128) (code-char b) #\?))
                    (loop for i from 0 below 400 for b = (sb-sys:sap-ref-8 ptr i) until (zerop b) collect b))
          (sb-alien:alien-funcall (sb-alien:extern-alien "free" (function sb-alien:void sb-sys:system-area-pointer)) ptr)))))
(defvar *keys* (vector #xD0C591 #xC841474 #x11D1FAD #x12F86037 #x35ED22C))
(defvar *initial* (diag-raw-ph *keys*))
(format t "~&;; initial: ~S~%" *initial*)
(let ((n 0) (out *error-output*))
  (dolist (name (rt:pending-tests))
    (let ((*standard-output* (make-broadcast-stream)) (*error-output* (make-broadcast-stream)))
      (rt:do-test name))
    (incf n) (format out "~&;; test ~D ~A~%" n name) (finish-output out)
    (let ((now (diag-raw-ph *keys*)))
      (unless (equal now *initial*)
        (format out "~&;; CHANGED after test ~D ~A: ~S~%" n name now)
        (let ((again (diag-raw-ph *keys*)))
          (format out ";; again: ~S~%" again))
        (finish-output out)
        (return)))
    (when (>= n 6725) (format out "~&;; no change through ~D tests~%" n) (return))))
(sb-ext:exit)
